In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_2009 = pd.read_csv('2009-_.csv')
data_2010 = pd.read_csv('2010-_.csv')
data_2011 = pd.read_csv('2011-_.csv')
data_2012 = pd.read_csv('2012-_.csv')
data_2013 = pd.read_csv('2013-_.csv')
data_2014 = pd.read_csv('2014-_.csv')
data_2015 = pd.read_csv('2015-_.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,4,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,82,83,85,86,87,89,90,91,93,94,95,97,98,99,101,102,103,105,106,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,194,195,197,199,201,203,205,207,209,211,213,215,217,219,220,221,222,223,225,227,229,231,232,233,235,237,239,241,242,244,246,248,250,252,254,256,258,260,262,264,266,268,270,272,274,276,278,279,280,281,282,283,284,285,286,287,288,290,291,292,293,294,296,298,300,302,304,305,306,308,310,311,312,314,316,318,320,322,324,325,326,328,330,332,334,336,338,340,342,344,346,348,350,352,354,356,358,360,362,364,366,368,370,372,374,376,378,380,382,384,386,388,390,392,394,396,398,400,402,404,406,408,410,412,414,416,418,420,422,424,426,428,430,432,434,436,438,440,442,444,446,448,450,452,454,456,458,460,462,464,466,468,470,472,474,476,478,479,480,481,482,484,486,488,490,492,494,496,498,500,502,504,506,508,510,512,513,514,515,516,517,518,520,522,524,526,528,530,532,534,536,538,539,540,541,542,544,546,548,550,552,554,556,558,560,562,564,566,568,570,572,574,576,578,580,582,584,586,588,590,592,594,596,598,600,602,604,606,608,610,612,614,616,618,620,622,624,626,628,630,632,634,635,636,638,640,642,644,646,648,650,652,654,656,658,660,662,664,666,668,670,672,674,676,678,680,682,684,686,688,690,692,694,696,698,700,702,704,706,708,710,712,714,716,718,720,722,724,726,728,730,732,734,736,738,740,742,744,746,748,750,752,754,756,758,760,762,764,766,768,770,772,774,776,778,780,782,784,786,788,790,792,794,796,798,800,802,804,806) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,4,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,60,62,63,64,65,66,67,69,70,71,72,74,75,76,78,79,81,82,83,85,86,87,89,90,91,93,94,95,97,98,99,101,102,103,105,106,107,109,110,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,144,145,147,150,152,154,155,156,158,159,160,161,162,163,164,166,168,170,172,175,177,179,181,183,185,187,188,189,191,193,195,197,198,199,200,201,203,205,207,208,209,210,211,213,215,217,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,266,267,269,271,273,274,275,277,279,281,283,285,287,289,291,293,295,297,298,299,301,303,304,305,306,307,308,309,311,312,313,315,317,319,321,323,325,327,329,331,333,335,337,339,341,343,345,347,349,351,353,355,357,359,361,363,365,367,369,371,373,375,377,379,381,383,384,385,387,389,391,393,395,397,399,401,403,404,405,407,409,411,413,415,416,417,418,419,421,423,425,427,428,430,432,434,436,438,440,442,444,446,448,450,452,454,456,458,460,462,464,465,466,467,468,469,470,471,472,473,474,476,477,478,479,480,482,484,486,488,490,492,494,496,498,500,502,503,505,507,509,511,512,513,515,517,519,521,523,525,527,529,531,533,535,537,539,541,543,545,547,549,551,553,555,557,559,561,563,565,567,569,571,573,575,577,579,581,583,585,587,589,591,593,595,597,599,601,603,605,607,609,611,613,615,617,618,619,620,621,623,625,627,629,631,633,635,637,639,641,643,645,647,650,652,655,657,660,662,664,666,668,670,672,673,674,675,676,678,680,682,684,686,688,690,692,693,694,695,696,698,700,702,703,705,707,709,711,713,715,717,719,721,723,725,727,729,731,733,735,737,739,741,743,745,747,749,751,753,755,757,759,761,763,765,767,769,771,773,775,777,779,781,783,785,787,789,791,793,795,797,799,801,803,805,807,809,811,813,815,817,819,821,823,825,827,829,831,833,835,837,839,841,843,845,847,849,851,853,855,857,859,861,863,865,867,869,871,873,875,877,879,881,883,885,887,889,891,893,895) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,5,7,9,11,13,15,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,49,51,52,53,54,55,56,58,59,60,62,63,64,66,67,68,70,71,73,74,75,77,78,79,81,82,83,85,86,87,89,90,91,93,94,95,97,98,99,101,102,103,105,107,109,111,113,115,117,119,121,123,125,126,127,128,129,130,131,132,133,134,135,137,139,142,144,146,148,150,152,154,156,157,158,159,160,161,162,164,166,168,170,172,174,175,176,177,178,179,180,181,182,184,185,186,187,188,189,190,191,192,193,194,195,196,198,200,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,224,226,228,230,232,234,236,237,238,240,242,244,246,247,248,249,250,251,252,254,256,258,260,262,264,266,267,268,269,270,272,274,275,276,277,278,279,280,282,283,284,285,286,287,288,289,290,291,292,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,324,326,328,330,332,334,336,337,338,339,340,342,344,346,348,349,350,351,352,353,354,355,356,358,360,362,363,364,365,366,367,368,370,372,374,376,377,378,379,380,381,382,384,386,388,390,392,393,394,395,396,397,398,400,402,404,405,406,407,408,409,410,411,412,414,416,418,420,422,424,425,426,427,428,429,430,431,432,434,436,437,438,439,440,441,442,443,444,445,446,448,450,452,453,454,455,456,457,458,460,462,464,466,468,470,472,473,474,475,476,477,478,479,480,482,484,486,488,490,492,494,496,498,500,502,504,506,508,510,512,514,516,518,520,522,524,526,528,530,532,534,536,538,540,542,544,546,548,549,550,551,552,553,554,555,556,558,560,561,562,563,564,565,566,567,568,569,570,572,574,575,576,578,580,582,584,586,588,590,592,594,596,598,599,600,602,604,606,608,609,610,611,612,613,614,616,617,618,619,620,621,622,624,626,628,630,631,632,633,634,635,636,637,638,640,642,644,645,646,647,648,649,650,652,654,656,658,659,660,661,662,663,664,666,668,670,672,673,674,675,676,677,678,679,680,682,684,686,687,688,689,690,691,692,693,694,696,698,700,702,703,704,705,706,707,708,709,710,712,714,716,718,720,722,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,782,784,786,788,790,792,794,796,797,798,799,800,802,803,804,805,806,807,808,809,810,811,812,814,816,818,819,820,821,822,823,824,825,826,828,830,831,832,833,834,835,836,837,838,839,840,842,844,845,846,847,848,849,850,851,852,854,856,858,860,861,862,863,864,865,866,867,868,870,872,873,874,875,876,877,878,879,880,881,882,884,886,888,889,890,891,892,893,894,895,896,898,900,902,904,906,908,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,958,959,960,961,962,963,964,965,966,967,968,970,972,974,976,978,980,981,982,983,984,985,986,987,988,989,990,991,992,994,995,996,997,998,1000,1002,1004,1006,1007,1008,1009,1010,1012,1014,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1035,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1049,1050,1051,1053,1054,1055,1057,1059,1061,1063,1065,1067,1069,1070,1071,1072,1073,1075,1077,1079,1080,1082,1084,1086,1088,1089,1090,1092,1094,1096,1098,1100,1102,1104,1106,1108,1110,1112,1114,1116,1118,1120,1122,1124,1126,1128,1130,1132,1134,1136,1138,1140,1142,1144,1145,1146,1147,1148,1149,1150,1152,1153,1154,1155,1156,1158,1160,1162,1163,1164,1165,1166,1167,1168,1169,1170,1172,1174,1176,1178,1179,1180,1181,1182,1183,1184,1186,1188,1190,1192,1194,1196,1198,1199,1200,1201,1202,1203,1204,1205,1206,1208,1211,1213,1215,1218,1220,1222,1224,1226,1228,1230,1231,1232,1233,1234,1235,1236,1237,1238,1240,1241,1242,1243,1244,1245,1246,1248,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1272,1274,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1313,1315,1317,1319,1321,1323,1325,1327,1329,1331,1333,1335,1337,1339,1341,1343,1345,1347,1349,1351,1353,1355,1357,1359,1361,1363,1364,1365,1367,1368,1369,1370,1372,1373,1374,1376,1378,1380,1381,1384,1386,1387,1388,1389,1390,1391,1392,1393,1395,1397,1398,1399,1400,1401,1402,1403,1405,1407,1408,1409,1410,1411,1413,1415,1417,1420,1421,1422,1423,1424,1426,1428,1430,1432,1435,1436,1437,1438,1439,1440,1441,1442,1443,1445,1447,1450,1452,1453,1454,1455,1456,1458,1460,1462,1465,1467,1469,1471,1473,1475,1477,1480,1482,1484,1486,1488,1490,1492,1495,1497,1499,1501,1503,1505,1507,1510,1512,1514,1516,1518,1520,1522,1525,1527,1529,1531,1533,1535,1537,1540,1542,1544,1546,1548,1550,1552,1555,1557,1559,1561,1563,1565,1567,1570,1572,1574,1576,1578,1580,1582,1585,1587,1589,1591,1593,1595,1597,1600,1602,1604,1606,1608,1610,1612,1615,1617,1619,1621,1623,1625,1627,1630,1632,1634,1636,1638,1640,1642,1644,1646,1648,1650,1652,1654,1656,1658,1660,1662,1664,1665,1666,1667,1668,1669,1670,1671,1672,1674,1675,1676,1677,1678,1679,1680,1682,1684,1686,1688,1690,1692,1694,1696,1697,1698,1699,1700,1701,1702,1704,1706,1708,1710,1712,1714,1716,1718,1720,1722,1724,1726,1728,1730,1732,1734,1736,1738,1740,1742,1744,1746,1748,1750,1752,1754,1756,1758,1760,1762,1764,1766,1768,1770,1772,1774,1776,1778,1780,1782,1784,1786,1788,1790,1792,1794,1796,1798,1800,1802,1804,1806,1808,1810,1812,1814,1816,1818,1820,1822,1824,1826,1828,1830,1832,1834,1836,1838,1840,1842,1844,1846,1848,1850,1851,1852,1854,1856,1858,1860,1862,1864,1866,1868,1870,1872,1874,1876,1878,1880,1882,1884,1886,1888,1890,1892,1894,1895,1896,1898,1900,1902,1904,1906,1908,1910,1912,1914,1916,1917,1918,1920,1922,1924,1926,1928,1930,1932,1934,1936,1938,1939,1940,1942,1944,1946,1948,1950,1952,1954,1956,1958,1960,1961,1962,1964,1966,1968,1970,1972,1974,1976,1978,1980,1982,1983,1984,1986,1988,1990,1992,1994,1996,1998,2000,2002,2004,2005,2006,2008,2010,2012,2014,2016,2018,2020,2022,2024,2026,2027,2028,2029,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2049,2050,2052,2054,2056,2058,2060,2062,2064,2066,2068,2070,2071,2072,2074,2076,2078,2080,2082,2084,2086,2088,2090,2092,2093,2094,2096,2098,2100,2102,2104,2106,2108,2110,2112,2114,2115,2116,2118,2120,2122,2124,2126,2128,2130,2132,2134,2136,2137,2138,2140,2142,2144,2146,2148,2150,2152,2154,2156,2158,2159,2160,2162,2164,2166,2168,2170,2172,2174,2176,2178,2180,2181,2182,2184,2186,2188,2190,2192,2194,2196,2198,2200,2202,2203,2204,2205,2206,2207,2208,2210,2212,2214,2216,2218,2220,2222,2224,2225,2226,2227,2228,2229,2230,2232,2234,2236,2238,2240,2242,2244,2246,2247,2248,2249,2250,2252,2254,2256,2258,2260,2262,2264,2266,2268,2269,2270,2271,2272,2273,2274,2276,2278,2280,2282,2284,2286,2288,2290,2291,2292,2293,2294,2296,2298,2300,2302,2304,2306,2308,2310,2312,2313,2314,2315,2316,2317,2318,2320,2322,2324,2326,2328,2330,2332,2334,2335,2336,2337,2338,2339,2340,2342,2344,2346,2348,2350,2352,2354,2356,2357,2358,2359,2360,2361,2362,2364,2366,2368,2370,2372,2374,2376,2378,2379,2380,2381,2382,2383,2384,2386,2388,2390,2392,2394,2396,2398,2400,2401,2402,2403,2404,2405,2406,2408,2410,2412,2414,2416,2418,2420,2422,2423,2424,2425,2426,2427,2428,2430,2432,2434,2436,2438,2440,2442,2444,2445,2446,2447,2448,2449,2450,2452,2454,2456,2458,2460,2462,2464,2466,2467,2468,2469,2470,2471,2472,2474,2476,2478,2480,2482,2484,2486,2488,2489,2490,2491,2492,2493,2494,2496,2498,2500,2502,2504,2506,2508,2510,2511,2512,2513,2514,2515,2516,2518,2520,2522,2524,2526,2528,2530,2532,2533,2534,2535,2536,2537,2538,2540,2542,2544,2546,2548,2550,2552,2554,2555,2556,2557,2558,2559,2560,2562,2564,2566,2568,2570,2572,2574,2576,2577,2578,2579,2580,2581,2582,2584,2586,2588,2590,2592,2594,2596,2598,2599,2600,2601,2602,2603,2604,2606,2608,2610,2612,2614,2616,2618,2620,2621,2622,2623,2624,2625,2626,2628,2630,2632,2634,2636,2638,2640,2642,2643,2644,2645,2646,2647,2648,2650,2652,2654,2656,2658,2660,2662,2664,2665,2666,2667,2668,2670,2672,2674,2676,2678,2680,2682,2684,2686,2687,2688,2690,2692,2694,2696,2698,2700,2702,2704,2706,2708,2709,2710,2711,2712,2714,2716,2718,2720,2722,2724,2726,2728,2730,2732,2734,2736,2738,2740,2742,2744,2746,2748,2750,2752,2754,2756,2758,2760,2762,2764,2766,2768,2770,2772,2774,2776,2778,2780,2782,2784,2786,2788,2790,2792,2794,2796,2798,2800,2802,2804,2806,2808,2810,2812,2814,2816,2818,2820,2822) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,3,5,7,9,11,13,15,17,18,20,22,24,26,28,30,32,34,36,38,39,40,41,42,43,45,46,47,49,50,51,53,54,55,57,58,60,62,63,64,66,67,68,70,71,72,74,75,76,78,79,80,82,83,84,86,87,88,90,91,92,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,114,115,116,118,119,120,122,123,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,186,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,210,211,212,213,214,215,216,217,218,219,220,221,222,224,226,228,230,232,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,250,252,254,256,258,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,280,282,284,285,286,287,288,290,292,294,296,298,300,302,304,306,308,310,312,314,316,318,320,322,324,326,328,330,331,332,333,334,335,336,338,340,341,342,344,346,347,348,349,350,351,352,353,354,356,358,359,360,361,362,363,364,366,368,370,372,374,376,378,380,382,384,386,388,390,392,394,396,397,398,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,472,473,474,475,476,477,478,479,480,482,484,486,488,490,492,494,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,544,545,546,547,548,549,550,551,552,553,554,556,557,558,559,560,561,562,563,564,565,566,568,569,570,572,574,576,578,579,580,582,584,586,588,589,590,592,594,596,598,599,600,602,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,620,621,622,624,626,628,630,632,634,636,637,638,639,640,641,642,644,646,648,650,652,654,656,657,658,660,662,664,666,668,670,672,674,676,678,680,682,684,686,688,690,692,694,696,698,700,702,704,706,708,709,710,712,714,716,718,720,722,724,726,728,730,732,734,736,738,740,742,744,746,748,750,752,754,756,758,760,762,763,764,766,769,771,773,776,778,780,781,783,785,787,789,791,793,794,795,796,797,798,799,800,801,803,804,805,806,807,808,809,810,811,813,814,815,816,817,818,819,820,821,823,825,826,827,828,829,830,831,833,835,837,839,841,843,845,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,871,873,875,877,879,880,881,882,883,884,885,886,887,888,889,890,892,894,896,898,900,902,904,905,906,907,908,909,910,912,914,916,917,918,919,920,921,922,924,926,928,930,932,934,936,938,940,942,944,945,946,947,948,949,950,951,952,953,954,956,958,959,960,961,962,963,964,966,967,968,969,970,971,972,973,974,976,978,980,982,983,984,986,988,989,990,991,992,993,994,995,996,997,998,1000,1002,1003,1004,1005,1006,1008,1010,1012,1014,1016,1017,1018,1019,1020,1021,1022,1023,1024,1026,1028,1030,1032,1034,1036,1038,1040,1042,1044,1046,1048,1050,1052,1054,1056,1058,1060,1062,1064,1066,1068,1070,1072,1074,1076,1078,1080,1082,1083,1085,1087,1089,1091,1093,1095,1098,1100,1102,1104,1106,1108,1110,1112,1114,1116,1118,1120,1122,1124,1126,1128,1130,1132,1134,1136,1137,1138,1139,1140,1142,1143,1144,1146,1148,1150,1152,1154,1156,1158,1160,1162,1164,1165,1166,1168,1170,1172,1174,1176,1178,1180,1182,1184,1186,1187,1188,1190,1192,1194,1196,1198,1200,1202,1204,1206,1208,1209,1210,1212,1214,1216,1218,1220,1222,1224,1226,1228,1230,1231,1232,1234,1236,1238,1240,1242,1244,1246,1248,1250,1252,1253,1254,1256,1258,1260,1262,1264,1266,1268,1270,1272,1274,1275,1276,1278,1280,1282,1284,1286,1288,1290,1292,1294,1296,1297,1298,1300,1302,1304,1306,1308,1310,1312,1314,1316,1318,1319,1320,1322,1324,1326,1328,1330,1332,1334,1336,1338,1340,1341,1342,1344,1346,1348,1350,1352,1354,1356,1358,1360,1362,1363,1364,1366,1368,1370,1372,1374,1376,1378,1380,1382,1384,1385,1386,1388,1390,1392,1394,1396,1398,1400,1402,1404,1406,1407,1408,1409,1410,1412,1414,1416,1418,1420,1422,1424,1426,1428,1429,1430,1431,1432,1434,1436,1438,1440,1442,1444,1446,1448,1450,1451,1452,1453,1454,1456,1458,1460,1462,1464,1466,1468,1470,1472,1473,1474,1475,1476,1478,1480,1482,1484,1486,1488,1490,1492,1494,1495,1496,1497,1498,1500,1502,1504,1506,1508,1510,1512,1514,1516,1517,1518,1519,1520,1522,1524,1526,1528,1530,1532,1534,1536,1538,1539,1540,1542,1544,1546,1548,1550,1552,1554,1556,1558,1560,1561,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1583,1584,1586,1588,1590,1592,1594,1596,1598,1600,1602,1604,1605,1606,1608,1610,1612,1614,1616,1618,1620,1622,1624,1626,1627,1628,1630,1632,1634,1636,1638,1640,1642,1644,1646,1648,1649,1650,1651,1652,1654,1656,1658,1660,1662,1664,1666,1668,1670,1671,1672,1673,1674,1676,1678,1680,1682,1684,1686,1688,1690,1692,1693,1694,1695,1696,1698,1700,1702,1704,1706,1708,1710,1712,1714,1715,1716,1717,1718,1720,1722,1724,1726,1728,1730,1732,1734,1736,1737,1738,1739,1740,1742,1744,1746,1748,1750,1752,1754,1756,1758,1759,1760,1761,1762,1764,1766,1768,1770,1772,1774,1776,1778,1780,1781,1782,1783,1784,1786,1788,1790,1792,1794,1796,1798,1800,1802,1803,1804,1805,1806,1808,1810,1812,1814,1816,1818,1820,1822,1824,1825,1826,1827,1828,1830,1832,1834,1836,1838,1840,1842,1844,1846,1847,1848,1849,1850,1852,1854,1856,1858,1860,1862,1864,1866,1868,1869,1870,1871,1872,1874,1876,1878,1880,1882,1884,1886,1888,1890,1891,1892,1893,1894,1896,1898,1900,1902,1904,1906,1908,1910,1912,1913,1914,1915,1916,1918,1920,1922,1924,1926,1928,1930,1932,1934,1935,1936,1938,1940,1942,1944,1946,1948,1950,1952,1954,1956,1957,1958,1960,1962,1964,1966,1968,1970,1972,1974,1976,1978,1979,1980,1982,1984,1986,1988,1990,1992,1994,1996,1998,2000,2001,2002,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050,2052,2054,2056,2058,2060,2062,2064,2066,2068,2070,2072,2074,2076,2078,2080,2082,2084,2086,2088,2090,2092,2094,2096,2098,2100,2102,2104,2106,2108,2110,2111,2112,2114,2116,2118,2120,2122,2124,2126,2128,2130,2132,2133,2134,2136,2138,2140,2142,2144,2146,2148,2150,2152,2154,2156,2158,2160,2162,2164,2166,2168,2170,2172,2174,2176,2177,2178,2180,2182,2184,2186,2188,2190,2192,2194,2196,2198,2200,2202,2204,2206,2208,2210,2212,2214,2216,2218,2220,2222,2224,2226,2228,2230,2232,2234,2236,2238,2240,2242,2244,2246,2248,2250,2252,2254,2256,2258,2260,2262,2264,2266,2268,2270,2272,2274,2276,2278,2280,2282,2284,2286,2288,2290) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,89,90,91,92,93,94,96,97,98,100,101,102,104,105,106,108,109,111,113,115,116,117,118,119,120,121,122,123,124,125,127,128,129,131,132,133,135,136,137,139,140,141,143,144,145,147,148,149,151,152,153,155,156,157,159,160,161,163,164,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207,209,211,213,215,217,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,267,269,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,293,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,315,317,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,341,342,343,344,345,346,347,348,349,350,351,352,353,355,357,359,361,363,365,367,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,385,387,389,391,392,393,394,395,396,397,398,399,401,403,405,407,409,411,413,415,417,419,421,423,425,427,429,431,433,435,436,437,438,439,440,441,443,445,447,448,449,451,453,454,455,456,457,458,459,460,461,463,465,466,467,469,471,473,475,477,479,481,483,485,487,489,491,492,493,494,496,497,499,501,503,505,507,508,509,511,513,514,515,516,517,518,519,521,523,525,527,529,531,533,535,537,538,539,540,541,542,543,544,545,546,547,548,549,551,553,555,557,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,577,579,581,583,584,585,586,587,588,589,591,593,595,597,599,601,603,605,607,609,610,611,612,613,614,615,616,617,618,619,620,621,623,625,627,629,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,649,651,653,655,656,657,658,659,660,661,662,663,664,665,667,669,670,671,673,674,675,677,679,680,681,683,684,685,687,688,689,691,692,693,695,697,699,701,703,705,707,709,711,713,715,717,719,721,723,725,727,729,731,733,735,737,739,740,741,743,745,747,749,751,753,755,757,759,761,763,765,767,769,771,773,775,777,779,781,782,783,784,786,788,790,792,794,796,798,799,800,801,802,803,804,806,807,808,809,810,811,812,814,816,817,818,819,820,821,822,823,824,826,828,829,830,831,832,833,834,836,838,840,842,844,846,848,850,852,854,856,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,878,880,882,884,886,888,890,891,892,893,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,920,921,922,923,924,926,928,930,931,932,933,934,935,936,937,938,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,990,992,994,996,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1018,1020,1021,1022,1023,1024,1026,1028,1030,1032,1034,1036,1038,1040,1041,1042,1043,1044,1045,1046,1049,1051,1053,1054,1055,1056,1057,1058,1059,1060,1061,1063,1065,1067,1069,1070,1072,1074,1076,1078,1080,1082,1084,1085,1086,1087,1088,1089,1090,1091,1092,1094,1096,1098,1100,1102,1104,1105,1106,1107,1108,1109,1110,1112,1114,1116,1118,1119,1120,1121,1122,1124,1125,1126,1127,1128,1130,1132,1134,1136,1137,1138,1139,1140,1141,1142,1144,1146,1148,1150,1151,1152,1153,1154,1155,1156,1158,1160,1162,1164,1166,1168,1170,1172,1174,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1202,1204,1205,1207,1209,1211,1213,1215,1217,1220,1222,1224,1226,1228,1230,1232,1234,1236,1238,1240,1242,1244,1246,1248,1250,1252,1254,1256,1258,1260,1262,1264,1265,1266,1268,1270,1272,1274,1276,1278,1280,1282,1284,1286,1287,1288,1290,1292,1294,1296,1298,1300,1302,1304,1306,1308,1309,1310,1312,1314,1316,1318,1320,1322,1324,1326,1328,1330,1331,1332,1334,1336,1338,1340,1342,1344,1346,1348,1350,1352,1353,1354,1356,1358,1360,1362,1364,1366,1368,1370,1372,1374,1375,1376,1378,1380,1382,1384,1386,1388,1390,1392,1394,1396,1397,1398,1400,1402,1404,1406,1408,1410,1412,1414,1416,1418,1419,1420,1422,1424,1426,1428,1430,1432,1434,1436,1438,1440,1441,1442,1444,1446,1448,1450,1452,1454,1456,1458,1460,1462,1463,1464,1466,1468,1470,1472,1474,1476,1478,1480,1482,1484,1485,1486,1488,1490,1492,1494,1496,1498,1500,1502,1504,1506,1507,1508,1510,1512,1514,1516,1518,1520,1522,1524,1526,1528,1529,1530,1531,1532,1534,1536,1538,1540,1542,1544,1546,1548,1550,1551,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1573,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1595,1596,1598,1600,1602,1604,1606,1608,1610,1612,1614,1616,1617,1618,1620,1622,1624,1626,1628,1630,1632,1634,1636,1638,1639,1640,1642,1644,1646,1648,1650,1652,1654,1656,1658,1660,1661,1662,1664,1666,1668,1670,1672,1674,1676,1678,1680,1682,1683,1684,1686,1688,1690,1692,1694,1696,1698,1700,1702,1704,1705,1706,1708,1710,1712,1714,1716,1718,1720,1722,1724,1726,1727,1728,1730,1732,1734,1736,1738,1740,1742,1744,1746,1748,1749,1750,1752,1754,1756,1758,1760,1762,1764,1766,1768,1770,1771,1772,1773,1774,1776,1778,1780,1782,1784,1786,1788,1790,1792,1793,1794,1796,1798,1800,1802,1804,1806,1808,1810,1812,1814,1815,1816,1818,1820,1822,1824,1826,1828,1830,1832,1834,1836,1837,1838,1840,1842,1844,1846,1848,1850,1852,1854,1856,1858,1859,1860,1862,1864,1866,1868,1870,1872,1874,1876,1878,1880,1881,1882,1884,1886,1888,1890,1892,1894,1896,1898,1900,1902,1903,1904,1906,1908,1910,1912,1914,1916,1918,1920,1922,1924,1925,1926,1927,1928,1930,1932,1934,1936,1938,1940,1942,1944,1946,1947,1948,1949,1950,1952,1954,1956,1958,1960,1962,1964,1966,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1980,1982,1984,1986,1988,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2002,2004,2006,2008,2010,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2024,2026,2028,2030,2032,2034,2035,2036,2037,2038,2039,2040,2041,2042,2044,2046,2048,2050,2052,2054,2056,2057,2058,2059,2060,2061,2062,2064,2066,2068,2070,2072,2074,2076,2078,2079,2080,2081,2082,2084,2086,2088,2090,2092,2094,2096,2098,2100,2101,2102,2103,2104,2106,2108,2110,2112,2114,2116,2118,2120,2121,2122,2123,2124,2126,2128,2130,2132,2134,2136,2138,2140,2142,2143,2144,2145,2146,2148,2150,2152,2154,2156,2158,2160,2162,2164,2165,2166,2168,2170,2172,2174,2176,2178,2180,2182,2184,2186,2187,2188,2190,2192,2194,2196,2198,2200,2202,2204,2206,2208,2209,2210,2212,2214,2216,2218,2220,2222,2224,2226,2228,2230,2231,2232,2234,2236,2238,2240,2242,2244,2246,2248,2250,2252,2253,2254,2256,2258,2260,2262,2264,2266,2268,2270,2272,2274,2275,2276,2278,2280,2282,2284,2286,2288,2290,2292,2294,2296,2297,2298,2300,2302,2304,2306,2308,2310,2312,2314,2316,2318,2320,2322,2324,2326,2328,2330,2332,2334,2336,2338,2340,2342,2344,2346,2348,2350,2352,2354,2356,2358,2360,2362,2364,2366,2368,2370,2372,2374,2376,2378,2380,2382,2384,2386,2388,2390,2392,2394,2396,2398,2400,2402,2404,2406,2408,2410,2412) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,4,6,8,9,11,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,53,54,55,56,57,59,60,61,63,64,65,67,68,69,71,72,74,76,78,80,82,84,86,88,90,92,94,95,96,97,98,99,100,101,102,104,106,108,110,112,114,116,117,118,119,120,121,122,124,126,128,130,132,133,134,135,136,137,138,140,142,144,146,148,150,151,152,153,154,155,156,158,160,162,164,166,168,169,170,171,172,174,176,178,180,182,184,186,187,188,189,190,192,194,196,198,200,202,204,205,206,207,208,209,210,212,214,216,218,220,222,223,224,226,228,230,232,234,236,238,240,242,244,246,248,250,252,254,256,258,260,262,264,266,268,269,270,271,272,273,274,276,278,279,280,281,282,283,284,286,288,290,291,292,293,294,295,296,297,298,300,302,303,304,305,306,307,308,310,312,314,315,316,318,320,322,324,326,327,328,329,330,332,334,336,338,340,342,344,346,348,350,352,354,356,358,360,362,364,366,368,370,372,374,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,392,394,396,398,400,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,420,422,424,425,426,427,428,429,430,431,432,433,434,435,436,438,440,442,444,446,448,449,450,451,452,453,454,455,456,458,460,462,464,466,468,470,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,492,494,496,497,498,499,500,501,502,503,504,505,506,507,508,510,512,514,516,518,520,521,522,524,526,528,529,530,531,532,534,536,537,538,540,542,544,546,548,550,552,554,555,556,557,558,559,560,562,564,566,568,570,572,574,576,578,580,582,584,586,588,590,592,594,596,598,600,601,602,603,604,606,608,610,611,612,614,616,617,618,619,620,621,622,623,624,625,626,628,629,630,631,632,634,636,638,640,642,644,646,648,650,652,654,655,656,657,658,660,662,664,666,668,670,672,674,676,678,680,682,684,686,687,688,690,692,694,696,698,700,702,704,706,708,710,711,712,713,714,715,716,718,719,720,721,722,723,724,726,728,729,730,731,732,733,734,735,736,738,740,742,743,744,745,746,748,750,752,753,754,755,756,758,760,762,763,764,765,766,768,769,770,771,772,773,774,775,776,778,780,782,783,784,785,786,788,790,792,794,796,798,800,802,804,806,808,810,812,814,815,816,817,818,819,820,821,822,823,824,825,826,828,830,832,834,836,838,840,842,845,846,847,848,850,852,854,856,858,860,862,864,866,867,868,869,870,871,872,873,874,876,877,878,879,880,881,882,884,886,887,888,889,890,891,892,893,894,895,896,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,924,926,927,928,929,930,931,932,934,936,937,938,939,940,941,942,943,944,945,946,948,949,950,951,952,953,954,955,956,958,960,961,962,963,964,965,966,968,970,972,974,976,978,980,981,982,983,984,985,986,989,991,993,994,995,996,997,998,999,1000,1001,1003,1005,1007,1010,1012,1014,1016,1018,1020,1022,1023,1024,1026,1027,1028,1029,1030,1032,1034,1035,1036,1037,1038,1039,1040,1042,1043,1044,1045,1046,1048,1050,1051,1052,1054,1056,1058,1060,1062,1064,1066,1068,1070,1072,1074,1076,1078,1080,1082,1084,1086,1088,1090,1092,1094,1096,1098,1100,1102,1104,1106,1108,1109,1110,1112,1113,1114,1115,1116,1117,1118,1119,1120,1122,1124,1126,1128,1130,1132,1134,1136,1138,1139,1140,1141,1142,1143,1144,1145,1146,1148,1150,1152,1154,1156,1158,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1176,1178,1180,1182,1184,1185,1186,1187,1188,1190,1192,1194,1196,1198,1200,1202,1204,1206,1208,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1222,1224,1226,1228,1230,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1248,1250,1252,1254,1256,1258,1260,1262,1264,1266,1268,1270,1272,1274,1276,1278,1280,1281,1282,1283,1284,1285,1286,1287,1288,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1306,1308,1310,1311,1312,1314,1315,1316,1317,1318,1319,1320,1321,1322,1324,1326,1327,1328,1329,1330,1331,1333,1334,1336,1337,1338,1339,1340,1342,1344,1345,1346,1348,1350,1352,1353,1354,1356,1358,1359,1360,1362,1363,1364,1365,1366,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1380,1381,1382,1383,1384,1385,1386,1388,1390,1392,1394,1395,1396,1397,1398,1399,1400,1402,1404,1406,1408,1410,1412,1414,1416,1418,1420,1422,1424,1426,1428,1430,1432,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1460,1462,1463,1464,1465,1467,1469,1471,1473,1475,1477,1480,1482,1484,1486,1488,1490,1492,1494,1496,1498,1500,1502,1504,1506,1508,1510,1512,1514,1516,1518,1520,1522,1524,1526,1528,1530,1532,1534,1536,1538,1540,1542,1544,1546,1548,1550,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1596,1598,1600,1602,1604,1606,1608,1610,1612,1614,1616,1618,1620,1621,1622,1624,1626,1628,1630,1632,1634,1636,1638,1640,1642,1644,1646,1648,1650,1651,1652,1654,1656,1658,1660,1662,1664,1666,1668,1670,1672,1674,1676,1678,1679,1680,1681,1682,1684,1686,1688,1690,1692,1694,1696,1698,1700,1702,1704,1706,1708,1709,1710,1711,1712,1714,1716,1718,1720,1722,1724,1726,1728,1730,1732,1734,1736,1738,1739,1740,1741,1742,1744,1746,1748,1750,1752,1754,1756,1758,1760,1762,1764,1766,1768,1769,1770,1771,1772,1774,1776,1778,1780,1782,1784,1786,1788,1790,1792,1794,1796,1798,1799,1800,1802,1804,1806,1808,1810,1812,1814,1816,1818,1820,1822,1824,1826,1828,1829,1830,1832,1834,1836,1838,1840,1842,1844,1846,1848,1850,1852,1854,1856,1858,1859,1860,1862,1864,1866,1868,1870,1872,1874,1876,1878,1880,1882,1884,1886,1888,1889,1890,1892,1894,1896,1898,1900,1902,1904,1906,1908,1910,1912,1914,1916,1918,1920,1921,1922,1924,1926,1928,1930,1932,1934,1936,1938,1940,1942,1944,1946,1948,1950,1951,1952,1954,1956,1958,1960,1962,1964,1966,1968,1970,1972,1974,1976,1978,1980,1981,1982,1984,1986,1988,1990,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2011,2012,2014,2016,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2041,2042,2044,2046,2048,2050,2052,2054,2056,2058,2060,2062,2064,2066,2068,2070,2071,2072,2074,2076,2078,2080,2082,2084,2086,2088,2090,2092,2094,2096,2098,2100,2101,2102,2104,2106,2108,2110,2112,2114,2116,2118,2120,2122,2124,2126,2128,2130,2131,2132,2134,2136,2138,2140,2142,2144,2146,2148,2150,2152,2154,2156,2158,2160,2161,2162,2163,2164,2166,2168,2170,2172,2174,2176,2178,2180,2182,2184,2186,2188,2190,2191,2192,2194,2196,2198,2200,2202,2204,2206,2208,2210,2212,2214,2216,2218,2220,2221,2222,2224,2226,2228,2230,2232,2234,2236,2238,2240,2242,2244,2246,2248,2250,2251,2252,2254,2256,2258,2260,2262,2264,2266,2268,2270,2272,2274,2276,2278,2280,2281,2282,2284,2286,2288,2290,2292,2294,2296,2298,2300,2302,2304,2306,2308,2310,2311,2312,2314,2316,2318,2320,2322,2324,2326,2328,2330,2332,2334,2336,2338,2340,2341,2342,2344,2346,2348,2350,2352,2354,2356,2358,2360,2362,2364,2366,2368,2370,2371,2372,2374,2376,2378,2380,2382,2384,2386,2388,2390,2392,2394,2396,2398,2400,2401,2402,2404,2406,2408,2410,2412,2414,2416,2418,2420,2422,2424,2426,2428,2430,2431,2432,2434,2436,2438,2440,2442,2444,2446,2448,2450,2452,2454,2456,2458,2460,2461,2462,2464,2466,2468,2470,2472,2474,2476,2478,2480,2482,2484,2486,2488,2490,2491,2492,2494,2496,2498,2500,2502,2504,2506,2508,2510,2512,2514,2516,2518,2520,2521,2522,2524,2526,2528,2530,2532,2534,2536,2538,2540,2542,2544,2546,2548,2550,2551,2552,2553,2554,2556,2558,2560,2562,2564,2566,2568,2570,2572,2574,2576,2578,2580,2581,2582,2583,2584,2586,2588,2590,2592,2594,2596,2598,2600,2602,2604,2606,2608,2610,2611,2612,2613,2614,2616,2618,2620,2622,2624,2626,2628,2630,2632,2634,2636,2638,2640,2641,2642,2644,2646,2648,2650,2652,2654,2656,2658,2660,2662,2664,2666,2668,2670,2671,2672,2674,2676,2678,2680,2682,2684,2686,2688,2690,2692,2694,2696,2698,2700,2701,2702,2704,2706,2708,2710,2712,2714,2716,2718,2720,2722,2724,2726,2728,2730,2731,2732,2733,2734,2736,2738,2740,2742,2744,2746,2748,2750,2752,2754,2756,2758,2760,2761,2762,2763,2764,2765,2766,2768,2770,2772,2774,2776,2778,2780,2782,2784,2786,2788,2790,2791,2792,2793,2794,2795,2796,2798,2800,2802,2804,2806,2808,2810,2812,2814,2816,2818,2820,2821,2822,2823,2824,2825,2826,2828,2830,2832,2834,2836,2838,2840,2842,2844,2846,2848,2850,2851,2852,2853,2854,2855,2856,2858,2860,2862,2864,2866,2868,2870,2872,2874,2876,2878,2880,2881,2882,2883,2884,2885,2886,2888,2890,2892,2894,2896,2898,2900,2902,2904,2906,2908,2910,2911,2912,2913,2914,2916,2918,2920,2922,2924,2926,2928,2930,2932,2934,2936,2938,2940,2941,2942,2943,2944,2946,2948,2950,2952,2954,2956,2958,2960,2962,2964,2966,2968,2970,2971,2972,2973,2974,2976,2978,2980,2982,2984,2986,2988,2990,2992,2994,2996,2998,3000,3001,3002,3003,3004,3006,3008,3010,3012,3014,3016,3018,3020,3022,3024,3026,3028,3030,3031,3032,3033,3034,3036,3038,3040,3042,3044,3046,3048,3050,3052,3054,3056,3058,3060,3061,3062,3064,3066,3068,3069,3070,3072,3074,3075,3076,3077,3078,3080,3082,3083,3084,3085,3086,3088,3090,3091,3092,3093,3094,3096,3098,3099,3100,3101,3102,3104,3106,3107,3108,3110,3112,3114,3115,3116,3118,3120,3122,3123,3124,3126,3128,3130,3131,3132,3134,3136,3138,3140,3141,3142,3144,3146,3148,3149,3150,3152,3154,3156,3157,3158,3160,3162,3164,3165,3166,3168,3170,3172,3173,3174,3176,3178,3180,3181,3182,3184,3186,3188,3189,3190,3192,3194,3196,3197,3198,3200,3202,3204,3205,3206,3208,3210,3212,3213,3214,3216,3218,3220,3221,3222,3224,3226,3228,3229,3230,3232,3234,3236,3237,3238,3240,3242,3244,3245,3246,3248,3250,3252,3253,3254,3256,3258,3260,3261,3262,3264,3266,3268,3269,3270,3272,3274,3276,3277,3278,3280,3282,3284,3285,3286,3288,3290,3292,3293,3294,3296,3298,3300,3301,3302,3304,3306,3308,3309,3310,3311,3312,3314,3316,3317,3318,3319,3320,3322,3324,3325,3326,3327,3328,3330,3332,3333,3334,3336,3338,3340,3341,3342,3344,3346,3348,3349,3350,3352,3354,3356,3357,3358,3359,3360,3362,3364,3365,3366,3367,3368,3370,3372,3373,3374,3375,3376,3378,3380,3381,3382,3383,3384,3386,3388,3389,3390,3392,3394,3396,3397,3398,3399,3400,3402,3404,3405,3406,3407,3408,3410,3412,3413,3414,3415,3416,3418,3420,3421,3422,3423,3424,3426,3428,3429,3430,3431,3432,3434,3436,3437,3438,3440,3442,3444,3445,3446,3448,3450,3452,3454,3455,3456,3458,3460,3462,3463,3464,3465,3466,3468,3470,3472,3473,3474,3475,3476,3478,3480,3482,3483,3484,3485,3486,3488,3490,3492,3493,3494,3495,3496,3498,3500,3502,3503,3504,3506,3508,3510,3512,3513,3514,3516,3518,3520,3522,3523,3524,3526,3528,3530,3532,3533,3534,3536,3538,3540,3542,3544,3545,3546,3548,3550,3552,3554,3555,3556,3558,3560,3562,3564,3565,3566,3568,3570,3572,3574,3575,3576,3578,3580,3582,3584,3585,3586,3588,3590,3592,3594,3595,3596,3598,3600,3602,3604,3605,3606,3608,3610,3612,3614,3615,3616,3618,3620,3622,3624,3625,3626,3628,3630,3632,3634,3635,3636,3638,3640,3642,3644,3645,3646,3648,3650,3652,3654,3655,3656,3658,3660,3662,3664,3665,3666,3668,3670,3672,3674,3675,3676,3678,3680,3682,3684,3685,3686,3688,3690,3692,3694,3695,3696,3698,3700,3702,3704,3705,3706,3708,3710,3712,3714,3715,3716,3718,3720,3722,3724,3725,3726,3728,3730,3732,3734,3735,3736,3738,3740,3742,3744,3745,3746,3748,3750,3752,3754,3755,3756,3758,3760,3762,3764,3765,3766,3768,3770,3772,3774,3775,3776,3778,3780,3782,3784,3785,3786,3788,3790,3792,3794,3795,3796,3798,3800,3802,3804,3805,3806,3808,3810,3812,3814,3815,3816,3818,3820,3822,3824,3825,3826,3827,3828,3830,3832,3834,3835,3836,3837,3838,3840,3842,3844,3845,3846,3847,3848,3850,3852,3854,3855,3856,3857,3858,3860,3862,3864,3865,3866,3867,3868,3870,3872,3874,3875,3876,3877,3878,3880,3882,3884,3885,3886,3888,3890,3892,3894,3895,3896,3897,3898,3900,3902,3904,3905,3906,3907,3908,3910,3912,3914,3915,3916,3917,3918,3920) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,4,6,8,10,12,14,17,19,21,23,25,27,29,31,33,35,37,39,40,41,42,43,44,46,47,48,50,51,52,54,55,56,58,59,61,63,65,67,69,71,73,75,77,79,81,82,83,84,85,86,87,88,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,171,173,175,177,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,195,197,199,201,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,227,228,229,230,231,232,233,234,235,237,239,241,243,245,247,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,271,273,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,293,295,297,299,300,301,302,303,304,305,306,307,309,311,313,315,317,319,321,323,325,327,329,331,333,335,337,339,341,343,344,345,346,347,348,349,350,351,353,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,405,406,407,408,409,411,413,415,417,419,421,423,425,427,429,430,431,432,433,435,437,439,441,443,445,447,449,451,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,523,524,525,526,527,528,529,530,531,533,535,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,563,565,567,568,569,570,571,573,575,577,578,579,580,581,582,583,585,587,588,589,590,591,592,593,594,595,597,598,599,600,601,602,603,604,605,607,608,609,610,611,612,613,615,617,618,619,620,621,623,625,627,628,629,630,631,632,633,635,637,638,639,640,641,642,643,644,645,646,647,649,651,652,653,654,655,656,657,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,683,686,688,689,690,691,692,693,694,695,696,698,700,702,704,706,708,710,712,714,716,717,718,719,720,721,722,723,724,726,728,730,732,734,736,738,740,742,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,766,768,770,772,773,774,776,778,780,782,784,786,788,790,792,793,794,795,796,797,798,799,800,801,802,804,806,808,810,812,814,815,816,817,818,819,820,821,822,824,825,826,827,828,830,832,834,836,837,838,839,840,841,842,843,844,846,848,849,850,851,852,853,854,856,858,860,862,863,864,865,866,867,868,870,872,873,874,875,876,878,880,882,884,886,888,890,892,894,895,896,897,898,900,901,902,903,904,905,906,907,908,910,911,912,913,914,916,918,920,922,924,926,928,930,932,934,936,938,940,942,944,946,948,950,952,954,956,958,960,962,964,965,966,967,968,969,970,971,972,974,975,976,977,978,979,980,981,982,983,984,985,986,988,990,992,994,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1012,1014,1016,1018,1020,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1034,1036,1038,1040,1042,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1056,1058,1060,1062,1064,1066,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1090,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1106,1108,1110,1112,1114,1116,1118,1120,1122,1124,1126,1128,1130,1132,1134,1136,1138,1140,1142,1143,1144,1145,1146,1147,1148,1149,1150,1152,1154,1155,1156,1157,1158,1159,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1182,1184,1185,1186,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1200,1202,1204,1206,1207,1208,1209,1210,1212,1214,1216,1218,1220,1221,1222,1223,1224,1226,1228,1230,1232,1234,1236,1238,1240,1242,1244,1246,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1286,1288,1289,1290,1291,1293,1295,1297,1299,1301,1303,1304,1306,1308,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1332,1334,1336,1338,1340,1342,1344,1346,1348,1350,1352,1354,1356,1358,1360,1362,1364,1366,1368,1370,1372,1374,1376,1378,1380,1382,1384,1386,1388,1390,1392,1394,1396,1398,1400,1402,1404,1406,1408,1410,1412,1414,1416,1418,1420,1422,1424,1426,1428,1430,1432,1434,1436,1438,1440,1442,1444,1446,1448,1450,1452,1454,1455,1456,1458,1460,1462,1464,1466,1468,1470,1472,1474,1476,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1500,1502,1504,1506,1508,1510,1512,1514,1516,1518,1520,1522,1524,1526,1528,1530,1532,1534,1536,1538,1540,1542,1544,1546,1548,1550,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1596,1598,1600,1602,1604,1606,1608,1610,1612,1614,1616,1618,1620,1622,1623,1624,1626,1628,1630,1632,1634,1636,1638,1640,1642,1644,1646,1648,1650,1652,1654,1656,1658,1660,1662,1664,1666,1668,1670,1672,1674,1676,1678,1680,1682,1684,1686,1688,1690,1692,1694,1696,1698,1700,1702,1704,1706,1708,1710,1712,1714,1716,1718,1720,1722,1724,1726,1728,1730,1732,1734,1736,1738,1740,1742,1744,1746,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1786,1788,1790,1792,1794,1796,1798,1800,1802,1804,1806,1808,1810,1811,1812,1813,1814,1816,1818,1820,1822,1824,1826,1828,1830,1832,1834,1836,1838,1840,1841,1842,1844,1846,1848,1850,1852,1854,1856,1858,1860,1862,1864,1866,1868,1870,1871,1872,1874,1876,1878,1880,1882,1884,1886,1888,1890,1892,1894,1896,1898,1900,1901,1902,1904,1906,1908,1910,1912,1914,1916,1918,1920,1922,1924,1926,1928,1930,1931,1932,1934,1936,1938,1940,1942,1944,1946,1948,1950,1952,1954,1956,1958,1960,1961,1962,1964,1966,1968,1970,1972,1974,1976,1978,1980,1982,1984,1986,1988,1990,1991,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016,2018,2020,2021,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050,2051,2052,2054,2056,2058,2060,2062,2064,2066,2068,2070,2072,2074,2076,2078,2080,2081,2082,2083,2084,2086,2088,2090,2092,2094,2096,2098,2100,2102,2104,2106,2108,2110,2111,2112,2113,2114,2116,2118,2120,2122,2124,2126,2128,2130,2132,2134,2136,2138,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2162,2164,2166,2168,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2196,2198,2200,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2226,2228,2230,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2256,2258,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2278,2280,2282,2284,2286,2288,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2308,2310,2312,2314,2316,2318,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2340,2342,2344,2346,2348,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2370,2372,2374,2376,2378,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2398,2400,2402,2404,2406,2408,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2428,2430,2432,2434,2436,2438,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2454,2456,2458,2460,2462,2464,2466,2468,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2484,2486,2488,2490,2492,2494,2496,2498,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2514,2516,2518,2520,2522,2524,2526,2528,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2544,2546,2548,2550,2552,2554,2556,2558,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2574,2576,2578,2580,2582,2584,2586,2588,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2604,2606,2608,2610,2612,2614,2616,2618,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2634,2636,2638,2640,2642,2644,2646,2648,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2664,2666,2668,2670,2672,2674,2676,2678,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2694,2696,2698,2700,2702,2704,2706,2708,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2724,2726,2728,2730,2732,2734,2736,2738,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2754,2756,2758,2760,2762,2764,2766,2768,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2784,2786,2788,2790,2792,2794,2796,2798,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2814,2816,2818,2820,2822,2824,2826,2828,2830,2831,2832,2833,2834,2835,2836,2837,2838,2839,2840,2841,2842,2844,2846,2848,2850,2852,2854,2856,2858,2860,2861,2862,2863,2864,2865,2866,2867,2868,2869,2870,2871,2872,2874,2876,2878,2880,2882,2884,2886,2888,2890,2891,2892,2893,2894,2895,2896,2897,2898,2899,2900,2901,2902,2904,2906,2908,2910,2912,2914,2916,2918,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2932,2934,2936,2938,2940,2942,2944,2946,2948,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2962,2964,2966,2968,2970,2972,2974,2976,2978,2980,2982,2983,2984,2985,2986,2987,2988,2989,2990,2992,2994,2996,2998,3000,3002,3004,3006,3008,3010,3012,3013,3014,3015,3016,3017,3018,3019,3020,3022,3024,3026,3028,3030,3032,3034,3036,3038,3040,3042,3043,3044,3046,3048,3050,3052,3054,3056,3058,3060,3062,3064,3066,3068,3070,3072,3073,3074,3076,3078,3080,3082,3084,3086,3088,3090,3092,3094,3096,3098,3100,3101,3102,3103,3104,3105,3106,3108,3110,3112,3114,3116,3118,3120,3122,3124,3126,3128,3130,3131,3132,3133,3134,3135,3136,3138,3140,3142,3144,3146,3148,3150,3152,3154,3156,3158,3160,3161,3162,3163,3164,3165,3166,3168,3170,3172,3174,3176,3178,3180,3182,3184,3186,3188,3190,3191,3192,3193,3194,3195,3196,3198,3200,3202,3204,3206,3208,3210,3212,3214,3216,3218,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3245,3246,3247,3248,3249,3250,3251,3252,3253,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3264,3265,3266,3267,3268,3269,3270,3271,3272,3273,3274,3275,3276,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286,3287,3288,3289,3290,3291,3292,3293,3294,3295,3296,3297,3298,3299,3300,3301,3302,3303,3304,3305,3306,3307,3308,3309,3310,3311,3312,3313,3314,3315,3316,3317,3318,3319,3320,3321,3322,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332,3334,3335,3336,3337,3338,3339,3340,3342,3343,3344,3345,3346,3347,3348,3349,3350,3351,3352,3353,3354,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364,3365,3366,3367,3368,3369,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388,3389,3390,3391,3392,3393,3394,3395,3396,3397,3398,3399,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410,3411,3412,3413,3414,3415,3416,3417,3418,3419,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3447,3448,3449,3450,3451,3452,3453,3454,3455,3456,3457,3458,3459,3460,3461,3462,3463,3464,3465,3466,3467,3468,3469,3470,3471,3472,3473,3474,3475,3476,3477,3478,3479,3480,3481,3482,3483,3484,3485,3486,3487,3488,3489,3490,3491,3492,3493,3494,3495,3496,3497,3498,3499,3500,3501,3502,3503,3504,3505,3506,3507,3508,3509,3510,3511,3512,3513,3514,3515,3516,3517,3518,3519,3520,3521,3522,3523,3524,3525,3526,3527,3528,3529,3530,3531,3532,3533,3534,3535,3536,3537,3538,3539,3540,3542,3543,3544,3545,3546,3547,3548,3550,3551,3552,3553,3554,3555,3556,3558,3559,3560,3561,3562,3563,3564,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604,3605,3606,3607,3608,3609,3610,3611,3612,3613,3614,3615,3616,3617,3618,3619,3620,3621,3622,3623,3624,3625,3626,3627,3628,3629,3630,3631,3632,3633,3634,3635,3636,3637,3638,3639,3640,3641,3642,3643,3644,3645,3646,3647,3648,3649,3650,3651,3652,3653,3654,3655,3656,3657,3658,3659,3660,3661,3662,3663,3664,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674,3675,3676,3677,3678,3679,3680,3681,3682,3683,3684,3685,3686,3687,3688,3689,3690,3691,3692,3693,3694,3695,3696,3697,3698,3699,3700,3701,3702,3703,3704,3705,3706,3707,3708,3710,3712,3713,3714,3715,3716,3717,3718,3720,3722,3723,3724,3725,3726,3727,3728,3729,3730,3731,3732,3733,3734,3735,3736,3737,3738,3739,3740,3741,3742,3743,3744,3746,3747,3748,3749,3750,3751,3752,3753,3754,3756,3757,3758,3759,3760,3761,3762,3763,3764,3765,3766,3767,3768,3769,3770,3771,3772,3773,3774,3775,3776,3777,3778,3779,3780,3781,3782,3783,3784,3785,3786,3787,3788,3789,3790,3791,3792,3793,3794,3795,3796,3797,3798,3799,3800,3801,3802,3803,3804,3805,3806,3807,3808,3809,3810,3811,3812,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822,3823,3824,3825,3826,3827,3828,3829,3830,3831,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850,3851,3852,3853,3854,3855,3856,3857,3858,3859,3860,3861,3862,3863,3864,3865,3866,3867,3868,3869,3870,3871,3872,3873,3874,3875,3876,3877,3878,3879,3880,3881,3882,3883,3884,3885,3886,3887,3888,3889,3890,3891,3892,3893,3894,3895,3896,3897,3898,3899,3900,3901,3902,3903,3904,3905,3906,3907,3908,3909,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919,3920,3921,3922,3923,3924,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952,3953,3954,3955,3956,3957,3958,3959,3960,3961,3962,3963,3964,3965,3966,3967,3968,3969,3970,3971,3972,3973,3974,3975,3976,3977,3978,3979,3980,3981,3982,3983,3984,3985,3986,3987,3988,3989,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999,4000,4001,4002,4003,4004,4006,4007,4008,4009,4010,4011,4012,4013,4014,4016,4017,4018,4019,4020,4021,4022,4023,4024,4026,4027,4028,4029,4030,4031,4032,4033,4034,4036,4037,4038,4039,4040,4041,4042,4043,4044,4045,4046,4047,4048,4049,4050,4051,4052,4053,4054,4055,4056,4057,4058,4059,4060,4061,4062,4063,4064,4065,4066,4067,4068,4069,4070,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080,4081,4082,4083) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
# IPTV

iptv_09 = pd.DataFrame(pd.value_counts(data_2009['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_09')).rename({'예':'O', '아니오':'X'})
iptv_10 = pd.DataFrame(pd.value_counts(data_2010['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_10')).rename({'시청':'O', '비시청':'X'})
iptv_11 = pd.DataFrame(pd.value_counts(data_2011['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_11')).rename({'이용':'O', '비이용':'X'})
iptv_12 = pd.DataFrame(pd.value_counts(data_2012['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_12')).rename({'이용':'O', '비이용':'X'})
iptv_13 = pd.DataFrame(pd.value_counts(data_2013['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_13')).rename({'예':'O', '아니오':'X'})
iptv_14 = pd.DataFrame(pd.value_counts(data_2014['시청방송형태 IPTV_labels'].values, sort = True).rename('iptv_14')).rename({'이용':'O', '비이용':'X'})
iptv_15 = pd.DataFrame(pd.value_counts(data_2015['시청방송형태 IPTV _labels'].values, sort = True).rename('iptv_15')).rename({'이용':'O', '비이용':'X'})

IPTV = pd.concat([iptv_09, iptv_10, iptv_11, iptv_12, iptv_13, iptv_14, iptv_15], axis=1)
IPTV.loc['user percent[%]'] = 100*(IPTV.loc['O']/(IPTV.loc['O'] + IPTV.loc['X']))
IPTV

,iptv_09,iptv_10,iptv_11,iptv_12,iptv_13,iptv_14,iptv_15
X,5974.000000,5859.000000,5873.000000,5377.000000,5031.000,4578.000000,5443.00000
O,430.000000,550.000000,796.000000,1064.000000,1209.000,1464.000000,2110.00000
user percent[%],6.714553,8.581682,11.935822,16.519174,19.375,24.230387,27.93592

In [11]:
# IPTV 인지

IPTV_recognition_09 = pd.DataFrame(pd.value_counts(data_2009['IPTV 인지_labels'].values, sort = True).rename('IPTV_recognition_09'))
IPTV_recognition_10 = pd.DataFrame(pd.value_counts(data_2010['IPTV 인지_labels'].values, sort = True).rename('IPTV_recognition_10'))
IPTV_recognition_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 인지_labels'].values, sort = True).rename('IPTV_recognition_11'))
IPTV_recognition_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 인지_labels'].values, sort = True).rename('IPTV_recognition_12'))

pd.concat([IPTV_recognition_09, IPTV_recognition_10, IPTV_recognition_11, IPTV_recognition_12], axis=1)

,IPTV_recognition_09,IPTV_recognition_10,IPTV_recognition_11,IPTV_recognition_12
처음 들어본다,3280,3148,2073,2192
이름은 들어보았다,1641,1582,1952,1599
대충은 알고 있다,1038,1087,1723,1489
잘 알고 있다,445,592,921,1161

In [15]:
# IPTV 가입 의향

IPTV_intention_09 = pd.DataFrame(pd.value_counts(data_2009['IPTV 가입 의향_labels'].values, sort = True).rename('IPTV_intention_09')).rename({'가입 의향 있음':'O', '가입 의향 없음':'X'})
IPTV_intention_10 = pd.DataFrame(pd.value_counts(data_2010['IPTV 가입 의향_labels'].values, sort = True).rename('IPTV_intention_10')).rename({'가입 의향 있음':'O', '가입 의향 없음':'X'})
IPTV_intention_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 가입 의향_labels'].values, sort = True).rename('IPTV_intention_11')).rename({'있음':'O', '없음':'X'})
IPTV_intention_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 가입 의향_labels'].values, sort = True).rename('IPTV_intention_12')).rename({'있음':'O', '없음':'X'})

IPTV_intention = pd.concat([IPTV_intention_09, IPTV_intention_10, IPTV_intention_11, IPTV_intention_12], axis=1)
IPTV_intention.loc['A prospective buyer[%]'] = 100*(IPTV_intention.loc['O']/(IPTV_intention.loc['O'] + IPTV_intention.loc['X']))

IPTV_intention

,IPTV_intention_09,IPTV_intention_10,IPTV_intention_11,IPTV_intention_12
X,5726.000000,5618.000000,5634.00000,5226.000000
O,248.000000,246.000000,239.00000,151.000000
A prospective buyer[%],4.151322,4.195089,4.06947,2.808257

In [16]:
# IPTV 가입 의향 이유

IPTV_intention_reason_09 = pd.DataFrame(pd.value_counts(data_2009['IPTV 가입 의향 이유_labels'].values).rename('IPTV_intention_reason_09')).rename({'양방향 서비스(쇼핑,금융 등)를 이용하기 위하여':'양방향 서비스를 이용하기 위해', '유선전화/초고속 인터넷과 패키지 가입을 위해':'유선전화, 인터넷 등과의 결합 상품구성', '지상파 방송(KBS,MBC,SBS,EBS 등)을 잘 보기 위하여':'지상파 방송을 보기 위하여', '채널이 다양하므로':'다양한 채널'})
IPTV_intention_reason_10 = pd.DataFrame(pd.value_counts(data_2010['IPTV 가입 의향 이유_labels'].values).rename('IPTV_intention_reason_10')).rename({'양방향 서비스(쇼핑,금융 등)를 이용하기 위하여':'양방향 서비스를 이용하기 위해', '유선전화/초고속 인터넷과 패키지 가입을 위해':'유선전화, 인터넷 등과의 결합 상품구성', '지상파 방송(KBS,MBC,SBS,EBS 등)을 잘 보기 위하여':'지상파 방송을 보기 위하여', '채널이 다양하므로':'다양한 채널'})
IPTV_intention_reason_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 가입 의향 이유_labels'].values).rename('IPTV_intention_reason_11')).rename({'양방향 서비스(쇼핑,금융 등)를 이용하기 위하여':'양방향 서비스를 이용하기 위해', '유선전화/초고속 인터넷과 패키지 가입을 위해':'유선전화, 인터넷 등과의 결합 상품구성', '지상파 방송(KBS,MBC,SBS,EBS 등)을 잘 보기 위하여':'지상파 방송을 보기 위하여', '채널이 다양하므로':'다양한 채널'})
IPTV_intention_reason_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 가입 의향 이유_labels'].values).rename('IPTV_intention_reason_12')).rename({'보고 싶은 채널(프로그램)을 볼 수 있음':'보고 싶은 프로그램이 있어서','양방향 서비스(쇼핑, 금융 등)를 이용하기 위해':'양방향 서비스를 이용하기 위해', '지상파 방송(KBS, MBC, SBS, EBS 등)을 잘 보기 위해':'지상파 방송을 보기 위하여'})
IPTV_intention_reason_13 = pd.DataFrame(pd.value_counts(data_2013['IPTV 가입 의향 이유_labels'].values).rename('IPTV_intention_reason_13')).rename({'보고 싶은 채널(프로그램)을 볼 수 있음':'보고 싶은 프로그램이 있어서','원하시는 시간에 프로그램을 보기 위해':'원하는 시간에 프로그램을 보기 위해', '인터넷, 위성방송 등과의 결합 상품 구성':'유선전화, 인터넷 등과의 결합 상품구성', '지상파방송(KBS, MBC, SBS, EBS 등)을 잘 볼수 있음':'지상파 방송을 보기 위하여'})

IPTV_intention_reason = pd.concat([IPTV_intention_reason_09, IPTV_intention_reason_10, IPTV_intention_reason_11, IPTV_intention_reason_12, IPTV_intention_reason_13], axis=1)
IPTV_intention_reason

,IPTV_intention_reason_09,IPTV_intention_reason_10,IPTV_intention_reason_11,IPTV_intention_reason_12,IPTV_intention_reason_13
기타,13.0,6.0,3.0,4,3
다양한 채널,64.0,77.0,72.0,29,25
보고 싶은 프로그램이 있어서,50.0,30.0,42.0,47,13
양방향 서비스를 이용하기 위해,4.0,10.0,21.0,6,1
어학 또는 자녀 교육에 도움,NaN,NaN,NaN,4,5
원하는 시간에 프로그램을 보기 위해,72.0,74.0,79.0,35,10
"유선전화, 인터넷 등과의 결합 상품구성",24.0,26.0,14.0,6,7
지상파 방송을 보기 위하여,21.0,23.0,8.0,20,9

In [21]:
# IPTV 가입시기

IPTV_period_09 = pd.DataFrame(pd.value_counts(data_2009['IPTV 가입시기_labels'].values).rename('IPTV_period_09')).rename({'1년 이후-2년 이내':'1년-2년', '6개월 이후-1년 이내':'6개월-1년'})
IPTV_period_10 = pd.DataFrame(pd.value_counts(data_2010['IPTV 가입시기_labels'].values).rename('IPTV_period_10')).rename({'1년 이후-2년 이내':'1년-2년', '6개월 이후-1년 이내':'6개월-1년'})
IPTV_period_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 가입시기_labels'].values).rename('IPTV_period_11')).rename({'1년이후 - 2년이내':'1년-2년', '6개월- 1년 이내':'6개월-1년'})
IPTV_period_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 가입시기_labels'].values).rename('IPTV_period_12')).rename({'1년이후 - 2년이내':'1년-2년', '6개월- 1년 이내':'6개월-1년'})

pd.concat([IPTV_period_09, IPTV_period_10, IPTV_period_11, IPTV_period_12], axis=1)

        IPTV_period_09  IPTV_period_10  IPTV_period_11  IPTV_period_12
1년-2년               79              59              79              57
2년 이후               71              76              92              33
6개월 이내              37              37              20              17
6개월-1년              61              74              48              44

In [22]:
# IPTV 가입 의향 없는 이유1

IPTV_intention_reason_N_09 = pd.DataFrame(pd.value_counts(data_2009['IPTV 가입 의향 없는 이유1_labels'].values, sort = True).rename('IPTV_intention_reason_09'))
IPTV_intention_reason_N_10 = pd.DataFrame(pd.value_counts(data_2010['IPTV 가입 의향 없는 이유1_labels'].values, sort = True).rename('IPTV_intention_reason_10'))
IPTV_intention_reason_N_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 가입 의향 없는 이유1_labels'].values, sort = True).rename('IPTV_intention_reason_11'))
IPTV_intention_reason_N_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 가입 의향 없는 이유1_labels'].values, sort = True).rename('IPTV_intention_reason_12'))

pd.concat([IPTV_intention_reason_N_09, IPTV_intention_reason_N_10, IPTV_intention_reason_N_11, IPTV_intention_reason_N_12], axis=1)

,IPTV_intention_reason_09,IPTV_intention_reason_10,IPTV_intention_reason_11,IPTV_intention_reason_12
"KBS,MBC,SBS 등 지상파 방송으로 충분하므로",1287,1021,893,989
"가격(가입비,월 시청료)이 부담되어서",353,333,358,294
가입절차가 복잡할 것 같아서,15,20,68,21
기타,179,158,208,124
방송 화면 전송 상태가 안정적이지 않다고 해서,7,10,14,37
볼만한 프로그램이 없을 것 같아서,65,58,93,85
이용 방법이 복잡할 것 같아서,32,46,41,80
자녀 교육에 문제가 있을 것 같아서,83,105,90,101
"종합,중계유선방송/위성방송 이용으로 충분하므로",3705,3867,3869,3495

In [24]:
# IPTV 6개월 후 이용여부
                                                                                                                                                                                                                                                           
IPTV_using_6month_11 = pd.DataFrame(pd.value_counts(data_2011['IPTV 6개월 후 이용여부_labels'].values, sort = True).rename('IPTV_intention_reason_11'))
IPTV_using_6month_12 = pd.DataFrame(pd.value_counts(data_2012['IPTV 6개월 후 이용여부_labels'].values, sort = True).rename('IPTV_intention_reason_12'))
IPTV_using_6month_13 = pd.DataFrame(pd.value_counts(data_2013['IPTV 6개월 후 이용여부_labels'].values, sort = True).rename('IPTV_intention_reason_13')).rename({'IPTV 서비스를 계속 이용할 것이다':'계속 이용할 것이다', 'IPTV 서비스를 해지할 것이다':'해지할 것이다'})
IPTV_using_6month_14 = pd.DataFrame(pd.value_counts(data_2014['IPTV 6개월 후 이용여부_labels'].values, sort = True).rename('IPTV_intention_reason_14')).rename({'IPTV 서비스를 계속 이용할 것이다':'계속 이용할 것이다', 'IPTV 서비스를 해지할 것이다':'해지할 것이다'})
IPTV_using_6month_15 = pd.DataFrame(pd.value_counts(data_2015['IPTV 6개월 후 이용여부  _labels'].values, sort = True).rename('IPTV_intention_reason_15')).rename({'IPTV 서비스를 계속 이용할 것이다':'계속 이용할 것이다', 'IPTV 서비스를 해지할 것이다':'해지할 것이다'})

pd.concat([IPTV_using_6month_11, IPTV_using_6month_12, IPTV_using_6month_13, IPTV_using_6month_14, IPTV_using_6month_15], axis=1)

,IPTV_intention_reason_11,IPTV_intention_reason_12,IPTV_intention_reason_13,IPTV_intention_reason_14,IPTV_intention_reason_15
계속 이용할 것이다,758,1020,1190,1416,2055
해지할 것이다,38,44,19,48,55

In [30]:
# 종편채널 시청빈도

JP_frequency_12 = pd.DataFrame(pd.value_counts(data_2012['종편채널 시청빈도_labels'].values, sort = True).rename('JP_frequency_12')).rename({'전혀 안봄/이용안함':'X'})
JP_frequency_13 = pd.DataFrame(pd.value_counts(data_2013['종편채널 시청빈도_labels'].values, sort = True).rename('JP_frequency_13')).rename({'전혀 안봄/이용안함':'X'})
JP_frequency_14 = pd.DataFrame(pd.value_counts(data_2014['종편채널 시청빈도_labels'].values, sort = True).rename('JP_frequency_14')).rename({'전혀 안봄 /이용안함':'X', '한달에 1-3일':'한달에 3일 이하', '2-3달에 1-2일 이하':'2-3달에 2일 이하'})
JP_frequency_15 = pd.DataFrame(pd.value_counts(data_2015['종편채널 시청빈도 _labels'].values, sort = True).rename('JP_frequency_15')).rename({'전혀 안봄 /이용안함':'X', '한달에 1-3일':'한달에 3일 이하', '2-3달에 1-2일 이하':'2-3달에 2일 이하'})

pd.concat([JP_frequency_12, JP_frequency_13, JP_frequency_14, JP_frequency_15], axis=1)

,JP_frequency_12,JP_frequency_13,JP_frequency_14,JP_frequency_15
1주일에 1-2일,1076.0,1153.0,1091,1715
1주일에 3-4일,425.0,770.0,935,1576
1주일에 5-6일,160.0,423.0,574,1052
2-3달에 2일 이하,NaN,NaN,268,225
X,2884.0,1837.0,1170,909
매일,174.0,487.0,605,922
한달에 3일 이하,1133.0,977.0,492,421

In [33]:
# 지상파 방송 프로그램 시청방식 

JSP_way_09 = pd.DataFrame(pd.value_counts(data_2009['지상파 방송 프로그램 시청 방식1_10,11_labels'].values, sort = True).rename('JSP_way_09'))
JSP_way_10 = pd.DataFrame(pd.value_counts(data_2010['지상파 방송 프로그램 시청 방식1_10,11_labels'].values, sort = True).rename('JSP_way_10'))
JSP_way_11 = pd.DataFrame(pd.value_counts(data_2011['지상파 방송 프로그램 시청 방식1_10,11_labels'].values, sort = True).rename('JSP_way_11'))

pd.concat([JSP_way_09, JSP_way_10, JSP_way_11], axis=1)

                          JSP_way_09  JSP_way_10  JSP_way_11
DMB                              NaN         NaN        21.0
DMB 서비스를 이용해서                   29.0         NaN         NaN
IPTV                             NaN        48.0         NaN
PMP                              NaN         NaN         1.0
TV에 정규 편성되어 방영되는 프로그램         6164.0         NaN         NaN
기타                              96.0         NaN         NaN
무응답                              NaN        68.0         NaN
방송국 인터넷 사이트에서 다시 보기를 통해서        77.0         NaN         NaN
본적없음                             NaN         NaN        93.0
스마트폰                             NaN         NaN        14.0
인터넷 실시간 방송이나 다시 보기               NaN        91.0         NaN
지상파 DMB 수신기                      NaN        34.0         NaN
컴퓨터                              NaN         NaN        52.0
컴퓨터로 동영상 파일 재생                   NaN        18.0         NaN
텔레비전                             NaN      6150.0         NaN
텔레비젼                             NaN         NaN      6488.0
프로그램 동영상 파일을 다운 받아서             38.0         NaN         NaN

In [123]:
# 시청방송형태 지상파 

JSP_user_09 = pd.DataFrame(pd.value_counts(data_2009['시청방송형태 지상파_labels'].values, sort = True).rename('JSP_user_09')).rename({'예':'O', '아니오':'X'})
JSP_user_10 = pd.DataFrame(pd.value_counts(data_2010['지상파TV 시청여부_labels'].values, sort = True).rename('JSP_user_10')).rename({'시청':'O', '비시청':'X'})
JSP_user_11 = pd.DataFrame(pd.value_counts(data_2011['시청방송형태 지상파_labels'].values, sort = True).rename('JSP_user_11')).rename({'이용':'O', '비이용':'X'})
JSP_user_12 = pd.DataFrame(pd.value_counts(data_2012['시청방송형태 지상파_labels'].values, sort = True).rename('JSP_user_12')).rename({'이용':'O', '비이용':'X'})
JSP_user_13 = pd.DataFrame(pd.value_counts(data_2013['시청방송형태 지상파_labels'].values, sort = True).rename('JSP_user_13')).rename({'예':'O', '아니오':'X'})
JSP_user_14 = pd.DataFrame(pd.value_counts(data_2014['시청방송형태 지상파_labels'].values, sort = True).rename('JSP_user_14')).rename({'이용':'O', '비이용':'X'})
JSP_user_15 = pd.DataFrame(pd.value_counts(data_2015['시청방송형태 지상파 _labels'].values, sort = True).rename('JSP_user_15')).rename({'이용':'O', '비이용':'X'})

pd.concat([JSP_user_09, JSP_user_10, JSP_user_11, JSP_user_12, JSP_user_13, JSP_user_14, JSP_user_15], axis=1)

,JSP_user_09,JSP_user_10,JSP_user_11,JSP_user_12,JSP_user_13,JSP_user_14,JSP_user_15
X,5672,5873,6144,5970,5853,5659,7183
O,732,536,525,471,387,383,370

In [126]:
# 시청방송형태 유선

US_user_09 = pd.DataFrame(pd.value_counts(data_2009['시청방송형태 유선_labels'].values, sort = True).rename('US_user_09')).rename({'예':'O', '아니오':'X'})
US_user_10 = pd.DataFrame(pd.value_counts(data_2010['시청방송형태 유선_labels'].values, sort = True).rename('US_user_10')).rename({'시청':'O', '비시청':'X'})
US_user_11 = pd.DataFrame(pd.value_counts(data_2011['시청방송형태 유선_labels'].values, sort = True).rename('US_user_11')).rename({'이용':'O', '비이용':'X'})
US_user_12 = pd.DataFrame(pd.value_counts(data_2012['시청방송형태 유선_labels'].values, sort = True).rename('US_user_12')).rename({'이용':'O', '비이용':'X'})
US_user_13 = pd.DataFrame(pd.value_counts(data_2013['시청방송형태 유선_labels'].values, sort = True).rename('US_user_13')).rename({'예':'O', '아니오':'X'})
US_user_14 = pd.DataFrame(pd.value_counts(data_2014['시청방송형태 유선_labels'].values, sort = True).rename('US_user_14')).rename({'이용':'O', '비이용':'X'})
US_user_15 = pd.DataFrame(pd.value_counts(data_2015['시청방송형태 유선 _labels'].values, sort = True).rename('US_user_15')).rename({'이용':'O', '비이용':'X'})


pd.concat([US_user_09, US_user_10, US_user_11, US_user_12, US_user_13, US_user_14, US_user_15], axis=1)

,US_user_09,US_user_10,US_user_11,US_user_12,US_user_13,US_user_14,US_user_15
O,5170,5194,5144,4671,4377,3927,4658
X,1234,1215,1525,1770,1863,2115,2895

In [127]:
# 시청방송형태 위성

WS_user_09 = pd.DataFrame(pd.value_counts(data_2009['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_09')).rename({'예':'O', '아니오':'X'})
WS_user_10 = pd.DataFrame(pd.value_counts(data_2010['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_10')).rename({'시청':'O', '비시청':'X'})
WS_user_11 = pd.DataFrame(pd.value_counts(data_2011['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_11')).rename({'이용':'O', '비이용':'X'})
WS_user_12 = pd.DataFrame(pd.value_counts(data_2012['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_12')).rename({'이용':'O', '비이용':'X'})
WS_user_13 = pd.DataFrame(pd.value_counts(data_2013['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_13')).rename({'예':'O', '아니오':'X'})
WS_user_14 = pd.DataFrame(pd.value_counts(data_2014['시청방송형태 위성_labels'].values, sort = True).rename('WS_user_14')).rename({'이용':'O', '비이용':'X'})
WS_user_15 = pd.DataFrame(pd.value_counts(data_2015['시청방송형태 위성 _labels'].values, sort = True).rename('WS_user_15')).rename({'이용':'O', '비이용':'X'})


pd.concat([WS_user_09, WS_user_10, WS_user_11, WS_user_12, WS_user_13, WS_user_14, WS_user_15], axis=1)

,WS_user_09,WS_user_10,WS_user_11,WS_user_12,WS_user_13,WS_user_14,WS_user_15
X,5987,5967,6178,5904,5726,5332,6853
O,417,442,491,537,514,710,700

In [131]:
# 지상파 방송 만족도

JSP_satisfi_09 = pd.DataFrame(pd.value_counts(data_2009['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_09'))
JSP_satisfi_10 = pd.DataFrame(pd.value_counts(data_2010['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_10'))
JSP_satisfi_11 = pd.DataFrame(pd.value_counts(data_2011['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_11'))
JSP_satisfi_12 = pd.DataFrame(pd.value_counts(data_2012['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_12'))
JSP_satisfi_13 = pd.DataFrame(pd.value_counts(data_2013['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_13'))
JSP_satisfi_14 = pd.DataFrame(pd.value_counts(data_2014['지상파 방송 만족도_labels'].values, sort = True).rename('JSP_satisfi_14'))
JSP_satisfi_15 = pd.DataFrame(pd.value_counts(data_2015['지상파 방송 만족도  _labels'].values, sort = True).rename('JSP_satisfi_15'))

pd.concat([JSP_satisfi_09, JSP_satisfi_10, JSP_satisfi_11, JSP_satisfi_12, JSP_satisfi_13, JSP_satisfi_14, JSP_satisfi_15], axis=1)

,JSP_satisfi_09,JSP_satisfi_10,JSP_satisfi_11,JSP_satisfi_12,JSP_satisfi_13,JSP_satisfi_14,JSP_satisfi_15
만족,2841,3267,3859,3537,3383,3045,4478
매우 만족,110,92,109,82,251,117,256
매우 불만족,38,42,14,34,25,28,24
무응답,16,23,32,52,148,246,222
보통,3171,2788,2525,2329,1898,2014,2088
불만족,228,197,130,142,126,164,87

In [132]:
# 유선방송 6개월 이후 이용여부

US_use_6_09 = pd.DataFrame(pd.value_counts(data_2009['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_09'))
US_use_6_10 = pd.DataFrame(pd.value_counts(data_2010['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_10'))
US_use_6_11 = pd.DataFrame(pd.value_counts(data_2011['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_11'))
US_use_6_12 = pd.DataFrame(pd.value_counts(data_2012['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_12'))
US_use_6_13 = pd.DataFrame(pd.value_counts(data_2013['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_13'))
US_use_6_14 = pd.DataFrame(pd.value_counts(data_2014['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_14'))
US_use_6_15 = pd.DataFrame(pd.value_counts(data_2015['유선방송 6개월 이후 이용여부  _labels'].values, sort = True).rename('US_use_6_15'))

pd.concat([US_use_6_09, US_use_6_10, US_use_6_11, US_use_6_12, US_use_6_13, US_use_6_14, US_use_6_15], axis=1)

,US_use_6_09,US_use_6_10,US_use_6_11,US_use_6_12,US_use_6_13,US_use_6_14,US_use_6_15
모름/무응답,NaN,20.0,34.0,26.0,28.0,NaN,NaN
유선방송을 계속 이용할 것이다,5051.0,5077.0,5021.0,4557.0,4307.0,NaN,NaN
유선방송을 해지할 것이다,119.0,91.0,89.0,88.0,42.0,NaN,NaN
케이블 방송을 계속 이용할 것이다,NaN,NaN,NaN,NaN,NaN,3860.0,4585.0
케이블 방송을 해지할 것이다,NaN,NaN,NaN,NaN,NaN,67.0,73.0

In [ ]:
# 해지 후 유료방송 이용 의견

US_use_6_09 = pd.DataFrame(pd.value_counts(data_2009['유선방송 6개월 이후 이용여부_labels'].values, sort = True).rename('US_use_6_09'))

In [39]:
# 라디오 이용빈도

radio_frequency_09 = pd.DataFrame(pd.value_counts(data_2009['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_09'))
radio_frequency_10 = pd.DataFrame(pd.value_counts(data_2010['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_10'))
radio_frequency_11 = pd.DataFrame(pd.value_counts(data_2011['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_11'))
radio_frequency_12 = pd.DataFrame(pd.value_counts(data_2012['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_12'))
radio_frequency_13 = pd.DataFrame(pd.value_counts(data_2013['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_13'))
radio_frequency_14 = pd.DataFrame(pd.value_counts(data_2014['라디오 이용빈도_labels'].values, sort = True).rename('radio_frequency_14'))
radio_frequency_15 = pd.DataFrame(pd.value_counts(data_2015['라디오 이용빈도 _labels'].values, sort = True).rename('radio_frequency_15'))

pd.concat([radio_frequency_09, radio_frequency_10, radio_frequency_11, radio_frequency_12, radio_frequency_13, radio_frequency_14, radio_frequency_15], axis=1)

,radio_frequency_09,radio_frequency_10,radio_frequency_11,radio_frequency_12,radio_frequency_13,radio_frequency_14,radio_frequency_15
1주일에 1-2일,399.0,588.0,375.0,397.0,297.0,368.0,464.0
1주일에 3-4일,404.0,385.0,443.0,373.0,368.0,336.0,454.0
1주일에 5-6일,508.0,540.0,482.0,376.0,354.0,331.0,358.0
2-3달에 1-2일 이하,94.0,88.0,95.0,120.0,68.0,98.0,209.0
매일,711.0,444.0,498.0,441.0,363.0,255.0,302.0
전혀 안 봄/이용 안함,4126.0,4254.0,4600.0,4564.0,4666.0,4419.0,5460.0
한 달에 1-2일,162.0,110.0,176.0,170.0,NaN,NaN,NaN
한 달에 1-3일,NaN,NaN,NaN,NaN,124.0,235.0,306.0

In [40]:
# 라디오 청취 경험

radio_experience_09 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_09'))
radio_experience_10 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_10'))
radio_experience_11 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_11'))
radio_experience_12 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_12'))
radio_experience_13 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_13'))
radio_experience_14 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 경험_labels'].values, sort = True).rename('radio_experience_14'))
radio_experience_15 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 경험  _labels'].values, sort = True).rename('radio_experience_15'))

pd.concat([radio_experience_09, radio_experience_10, radio_experience_11, radio_experience_12, radio_experience_13, radio_experience_14,radio_experience_15], axis=1)

,radio_experience_09,radio_experience_10,radio_experience_11,radio_experience_12,radio_experience_13,radio_experience_14,radio_experience_15
아니오,4280,4560,4786,4634,4694,4611,5854
예,2124,1849,1883,1807,1546,1431,1699

In [81]:
# 라디오 들은 장소

# 2009
R_place_09_1 = pd.DataFrame(pd.value_counts(data_2009['라디오 들은 장소1_labels'].values, sort = True))
R_place_09_2 = pd.DataFrame(pd.value_counts(data_2009['라디오 들은 장소2_labels'].values, sort = True))
R_place_09_3 = pd.DataFrame(pd.value_counts(data_2009['라디오 들은 장소3_labels'].values, sort = True))
R_place_09_4 = pd.DataFrame(pd.value_counts(data_2009['라디오 들은 장소4_labels'].values, sort = True))
R_place_09_5 = pd.DataFrame(pd.value_counts(data_2009['라디오 들은 장소5_labels'].values, sort = True))

R_place_09 = pd.concat([R_place_09_1, R_place_09_2, R_place_09_3, R_place_09_4, R_place_09_5], axis=1)
R_place_09['R_place_09']= R_place_09.iloc[:, 0:5].sum(axis=1)

# 2010
R_place_10_1 = pd.DataFrame(pd.value_counts(data_2010['라디오 들은 장소1_labels'].values, sort = True))
R_place_10_2 = pd.DataFrame(pd.value_counts(data_2010['라디오 들은 장소2_labels'].values, sort = True))
R_place_10_3 = pd.DataFrame(pd.value_counts(data_2010['라디오 들은 장소3_labels'].values, sort = True))

R_place_10 = pd.concat([R_place_10_1, R_place_10_2, R_place_10_3], axis=1)
R_place_10['R_place_10']= R_place_10.iloc[:, 0:3].sum(axis=1)

# 2011
R_place_11_1 = pd.DataFrame(pd.value_counts(data_2011['라디오 들은 장소1_labels'].values, sort = True))
R_place_11_2 = pd.DataFrame(pd.value_counts(data_2011['라디오 들은 장소2_labels'].values, sort = True))
R_place_11_3 = pd.DataFrame(pd.value_counts(data_2011['라디오 들은 장소3_labels'].values, sort = True))
R_place_11_4 = pd.DataFrame(pd.value_counts(data_2011['라디오 들은 장소4_labels'].values, sort = True))

R_place_11 = pd.concat([R_place_11_1, R_place_11_2, R_place_11_3, R_place_11_4], axis=1)
R_place_11['R_place_11']= R_place_11.iloc[:, 0:4].sum(axis=1)

# 2012
R_place_12_1 = pd.DataFrame(pd.value_counts(data_2012['라디오 들은 장소1_labels'].values, sort = True))
R_place_12_2 = pd.DataFrame(pd.value_counts(data_2012['라디오 들은 장소2_labels'].values, sort = True))
R_place_12_3 = pd.DataFrame(pd.value_counts(data_2012['라디오 들은 장소3_labels'].values, sort = True))
R_place_12_4 = pd.DataFrame(pd.value_counts(data_2012['라디오 들은 장소4_labels'].values, sort = True))

R_place_12 = pd.concat([R_place_12_1, R_place_12_2, R_place_12_3, R_place_12_4], axis=1)
R_place_12['R_place_12']= R_place_12.iloc[:, 0:4].sum(axis=1)

# 2013
R_place_13_1 = pd.DataFrame(pd.value_counts(data_2013['라디오 들은 장소1_labels'].values, sort = True))
R_place_13_2 = pd.DataFrame(pd.value_counts(data_2013['라디오 들은 장소2_labels'].values, sort = True))
R_place_13_3 = pd.DataFrame(pd.value_counts(data_2013['라디오 들은 장소3_labels'].values, sort = True))
R_place_13_4 = pd.DataFrame(pd.value_counts(data_2013['라디오 들은 장소4_labels'].values, sort = True))

R_place_13 = pd.concat([R_place_13_1, R_place_13_2, R_place_13_3, R_place_13_4], axis=1)
R_place_13['R_place_13']= R_place_13.iloc[:, 0:4].sum(axis=1)

# 2014
R_place_14_1 = pd.DataFrame(pd.value_counts(data_2014['라디오 들은 장소1_labels'].values, sort = True))
R_place_14_2 = pd.DataFrame(pd.value_counts(data_2014['라디오 들은 장소2_labels'].values, sort = True))
R_place_14_3 = pd.DataFrame(pd.value_counts(data_2014['라디오 들은 장소3_labels'].values, sort = True))
R_place_14_4 = pd.DataFrame(pd.value_counts(data_2014['라디오 들은 장소4_labels'].values, sort = True))

R_place_14 = pd.concat([R_place_14_1, R_place_14_2, R_place_14_3, R_place_14_4], axis=1)
R_place_14['R_place_14']= R_place_14.iloc[:, 0:4].sum(axis=1)

# 2015
R_place_15_1 = pd.DataFrame(pd.value_counts(data_2015['라디오 들은 장소1 _labels'].values, sort = True))
R_place_15_2 = pd.DataFrame(pd.value_counts(data_2015['라디오 들은 장소2 _labels'].values, sort = True))
R_place_15_3 = pd.DataFrame(pd.value_counts(data_2015['라디오 들은 장소3 _labels'].values, sort = True))
R_place_15_4 = pd.DataFrame(pd.value_counts(data_2015['라디오 들은 장소4 _labels'].values, sort = True))

R_place_15 = pd.concat([R_place_15_1, R_place_15_2, R_place_15_3, R_place_15_4], axis=1)
R_place_15['R_place_15']= R_place_15.iloc[:, 0:4].sum(axis=1)

R_place = pd.concat([R_place_09['R_place_09'], R_place_10['R_place_10'], R_place_11['R_place_11'], R_place_12['R_place_12'], R_place_13['R_place_13'], R_place_14['R_place_14'], R_place_15['R_place_15']], axis=1)
R_place['sum_radio_place']= R_place.iloc[:, 0:7].sum(axis=1)
R_place

,R_place_09,R_place_10,R_place_11,R_place_12,R_place_13,R_place_14,R_place_15,sum_radio_place
기타,61.0,39.0,27.0,48.0,45.0,26.0,40.0,286.0
대중교통수단,153.0,144.0,165.0,149.0,91.0,100.0,89.0,891.0
모름/무응답,NaN,NaN,14.0,4.0,2.0,NaN,1.0,21.0
사무실/직장/학교,275.0,199.0,243.0,189.0,126.0,128.0,161.0,1321.0
음식점/커피숍,19.0,9.0,28.0,16.0,11.0,15.0,9.0,107.0
자가용,1117.0,1057.0,1044.0,1003.0,935.0,896.0,1023.0,7075.0
집,862.0,623.0,658.0,647.0,527.0,448.0,592.0,4357.0

In [102]:
# 라디오 청취 방법

# 2009
R_way_09_1 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 방법1_labels'].values, sort = True))
R_way_09_2 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 방법2_labels'].values, sort = True))
R_way_09_3 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 방법3_labels'].values, sort = True))
R_way_09_4 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 방법4_labels'].values, sort = True))
R_way_09_5 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 방법5_labels'].values, sort = True))

R_way_09 = pd.concat([R_way_09_1, R_way_09_2, R_way_09_3, R_way_09_4, R_way_09_5], axis=1)
R_way_09['R_way_09']= R_way_09.iloc[:, 0:5].sum(axis=1)

# 2010
R_way_10_1 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 방법1_labels'].values, sort = True))
R_way_10_2 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 방법2_labels'].values, sort = True))
R_way_10_3 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 방법3_labels'].values, sort = True))
R_way_10_4 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 방법4_labels'].values, sort = True))

R_way_10 = pd.concat([R_way_10_1, R_way_10_2, R_way_10_3, R_way_10_4], axis=1)
R_way_10['R_way_10']= R_way_10.iloc[:, 0:4].sum(axis=1)

# 2011
R_way_11_1 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 방법1_labels'].values, sort = True))
R_way_11_2 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 방법2_labels'].values, sort = True))
R_way_11_3 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 방법3_labels'].values, sort = True))
R_way_11_4 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 방법4_labels'].values, sort = True))
R_way_11_5 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 방법5_labels'].values, sort = True))

R_way_11 = pd.concat([R_way_11_1, R_way_11_2, R_way_11_3, R_way_11_4, R_way_11_5], axis=1)
R_way_11['R_way_11']= R_way_11.iloc[:, 0:5].sum(axis=1)
R_way_11 = R_way_11.rename({'DMB 수신기를 통해/실시간 청취':'DMB수신기를 이용하여'})

# 2012
R_way_12_1 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 방법1_labels'].values, sort = True))
R_way_12_2 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 방법2_labels'].values, sort = True))
R_way_12_3 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 방법3_labels'].values, sort = True))
R_way_12_4 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 방법4_labels'].values, sort = True))
R_way_12_5 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 방법5_labels'].values, sort = True))

R_way_12 = pd.concat([R_way_12_1, R_way_12_2, R_way_12_3, R_way_12_4, R_way_12_5], axis=1)
R_way_12['R_way_12']= R_way_12.iloc[:, 0:5].sum(axis=1)
R_way_12 = R_way_12.rename({'DMB 수신기를 통해/실시간 청취':'DMB수신기를 이용하여',
                            'MP3,PMP,핸드폰 등에 있는 라디오를 통해/실시간 청취':'MP3/PMP,핸드폰 겸용 수신기를 이용하여',
                            '스마트폰 애플리케이션을 통해/실시간 청취':'스마트폰 어플리케이션을 이용하여'})

# 2013
R_way_13_1 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 방법1_labels'].values, sort = True))
R_way_13_2 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 방법2_labels'].values, sort = True))
R_way_13_3 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 방법3_labels'].values, sort = True))
R_way_13_4 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 방법4_labels'].values, sort = True))
R_way_13_5 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 방법5_labels'].values, sort = True))

R_way_13 = pd.concat([R_way_13_1, R_way_13_2, R_way_13_3, R_way_13_4, R_way_13_5], axis=1)
R_way_13['R_way_13']= R_way_13.iloc[:, 0:5].sum(axis=1)
R_way_13 = R_way_13.rename({'DMB 수신기를 통해/실시간 청취':'DMB수신기를 이용하여',
                            'MP3,PMP,핸드폰 등에 있는 라디오를 통해/실시간 청취':'MP3/PMP,핸드폰 겸용 수신기를 이용하여',
                            '스마트폰 애플리케이션을 통해/실시간 청취':'스마트폰 어플리케이션을 이용하여'})

# 2014
R_way_14_1 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 방법1_labels'].values, sort = True))
R_way_14_2 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 방법2_labels'].values, sort = True))
R_way_14_3 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 방법3_labels'].values, sort = True))
R_way_14_4 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 방법4_labels'].values, sort = True))
R_way_14_5 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 방법5_labels'].values, sort = True))

R_way_14 = pd.concat([R_way_14_1, R_way_14_2, R_way_14_3, R_way_14_4, R_way_14_5], axis=1)
R_way_14['R_way_14']= R_way_14.iloc[:, 0:5].sum(axis=1)
R_way_14 = R_way_14.rename({'DMB 수신기를 이용해서/실시간 청취':'DMB수신기를 이용하여',
                            'MP3,PMP 등 모바일 기기 겸용 수신기를 이용해서/실시간 청취':'MP3/PMP,핸드폰 겸용 수신기를 이용하여',
                            '모바일 및 스마트 기기를 이용해서/다시 듣기 청취(팟캐스트 포?':'모바일 및 스마트 기기를 통해/다시 듣기 청취(팟캐스트 포함)',
                            '스마트폰 애플리케이션을 이용해서/실시간 청취':'스마트폰 어플리케이션을 이용하여'})

# 2015
R_way_15_1 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 방법1 _labels'].values, sort = True))
R_way_15_2 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 방법2 _labels'].values, sort = True))
R_way_15_3 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 방법3 _labels'].values, sort = True))
R_way_15_4 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 방법4 _labels'].values, sort = True))
R_way_15_5 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 방법5 _labels'].values, sort = True))

R_way_15 = pd.concat([R_way_15_1, R_way_15_2, R_way_15_3, R_way_15_4, R_way_15_5], axis=1)
R_way_15['R_way_15']= R_way_15.iloc[:, 0:5].sum(axis=1)
R_way_15 = R_way_15.rename({'DMB 수신기를 이용해서/실시간 청취':'DMB수신기를 이용하여',
                            'MP3,PMP 등 모바일 기기 겸용 수신기를 이용해서/실시간 청취':'MP3/PMP,핸드폰 겸용 수신기를 이용하여',
                            '모바일 및 스마트 기기를 이용해서/다시 듣기 청취(팟캐스트 포?':'모바일 및 스마트 기기를 통해/다시 듣기 청취(팟캐스트 포함)',
                            '스마트폰 애플리케이션을 이용해서/실시간 청취':'스마트폰 어플리케이션을 이용하여'})

R_way = pd.concat([R_way_09['R_way_09'], R_way_10['R_way_10'], R_way_11['R_way_11'], R_way_12['R_way_12'], R_way_13['R_way_13'], R_way_14['R_way_14'], R_way_15['R_way_15']], axis=1)
R_way['sum_radio_way']= R_way.iloc[:, 0:7].sum(axis=1)
R_way

,R_way_09,R_way_10,R_way_11,R_way_12,R_way_13,R_way_14,R_way_15,sum_radio_way
DMB수신기를 이용하여,17.0,29.0,26.0,15.0,7.0,11.0,12.0,117.0
"MP3/PMP,핸드폰 겸용 수신기를 이용하여",88.0,51.0,72.0,50.0,32.0,12.0,12.0,317.0
기타,14.0,8.0,7.0,NaN,NaN,NaN,NaN,29.0
라디오 방송 파일을 별도로 다운 받아 듣는다,6.0,3.0,1.0,NaN,NaN,NaN,NaN,10.0
모바일 및 스마트 기기를 통해/다시 듣기 청취(팟캐스트 포함),NaN,NaN,NaN,13.0,17.0,24.0,40.0,94.0
스마트폰 어플리케이션을 이용하여,NaN,NaN,44.0,107.0,77.0,83.0,121.0,432.0
"아날로그 수신기(일반 라디오,오디오 포함)를 통해",1102.0,758.0,805.0,NaN,NaN,NaN,NaN,2665.0
"일반 라디오, 오디오를 통해/ 실시간 청취",NaN,NaN,NaN,798.0,598.0,NaN,NaN,1396.0
"일반 라디오,오디오를 이용해서/ 실시간 청취",NaN,NaN,NaN,NaN,NaN,573.0,687.0,1260.0
자동차 오디어의 라디오를 이용해서/실시간 청취,NaN,NaN,NaN,NaN,NaN,905.0,1036.0,1941.0
자동차에 있는 라디오를 통해/실시간 청취,NaN,NaN,NaN,1035.0,990.0,NaN,NaN,2025.0
차 안에 있는 카 오디오의 라디오로,1088.0,1080.0,1039.0,NaN,NaN,NaN,NaN,3207.0
컴퓨터에서 인터넷을 이용해서/ 실시간 청취,NaN,NaN,NaN,NaN,NaN,24.0,32.0,56.0
컴퓨터에서 인터넷을 이용해서/다시 듣기 청취(팟캐스트 포함),NaN,NaN,NaN,NaN,NaN,15.0,10.0,25.0
컴퓨터에서 인터넷을 통해 다시 듣기,NaN,NaN,13.0,NaN,NaN,NaN,NaN,13.0
컴퓨터에서 인터넷을 통해 실시간 청취,NaN,NaN,76.0,NaN,NaN,NaN,NaN,76.0
"컴퓨터에서 인터넷을 통해(KBS-콩,MBC-미니,SBS-고릴라 등을 통",67.0,NaN,NaN,NaN,NaN,NaN,NaN,67.0
"컴퓨터에서 인터넷을 통해(KBS-콩,MBC-미니,SBS-고릴라 등을 통?",NaN,92.0,NaN,NaN,NaN,NaN,NaN,92.0
컴퓨터에서 인터넷을 통해/ 실시간 청취,NaN,NaN,NaN,48.0,21.0,NaN,NaN,69.0
컴퓨터에서 인터넷을 통해/다시 듣기 청취,NaN,NaN,NaN,9.0,NaN,NaN,NaN,9.0
컴퓨터에서 인터넷을 통해/다시 듣기 청취(팟캐스트 포함),NaN,NaN,NaN,NaN,22.0,NaN,NaN,22.0
"택시,버스,식당 등에서 다른 사람이 틀어놓은 것으로",134.0,85.0,131.0,NaN,NaN,NaN,NaN,350.0

In [115]:
# 라디오 청취 이유

radio_reason_09 = pd.DataFrame(pd.value_counts(data_2009['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_09')).rename({'특별한 목적 없이 습관적으로':'습관적으로',
                                                                                                                                        '음악을 듣기 위해서':'음악을 듣기 위해',
                                                                                                                                        '새로운 정보나 지식을 얻기 위해서':'시사/보도 프로그램을 통해 정보나 지식을 얻기 위해'})
radio_reason_10 = pd.DataFrame(pd.value_counts(data_2010['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_10')).rename({'특별한 목적 없이 습관적으로':'습관적으로',
                                                                                                                                        '음악을 듣기 위해서':'음악을 듣기 위해',
                                                                                                                                        '새로운 정보나 지식을 얻기 위해서':'시사/보도 프로그램을 통해 정보나 지식을 얻기 위해'})
radio_reason_11 = pd.DataFrame(pd.value_counts(data_2011['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_11'))
radio_reason_12 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_12'))
radio_reason_13 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_13'))
radio_reason_14 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취 이유_12_labels'].values, sort = True).rename('radio_reason_14'))
radio_reason_15 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취 이유_12 _labels'].values, sort = True).rename('radio_reason_15'))

R_reason = pd.concat([radio_reason_09, radio_reason_10, radio_reason_11, radio_reason_12, radio_reason_13, radio_reason_14, radio_reason_15], axis=1)
R_reason['sum_radio_reason']= R_reason.iloc[:, 0:7].sum(axis=1)
R_reason

,radio_reason_09,radio_reason_10,radio_reason_11,radio_reason_12,radio_reason_13,radio_reason_14,radio_reason_15,sum_radio_reason
교통정보를 듣기 위해,NaN,NaN,146.0,70.0,101,87,102,506.0
기타,86.0,77.0,85.0,49.0,41,22,26,386.0
다른 사람이 틀어놓아서,NaN,NaN,NaN,85.0,74,69,77,305.0
모름/무응답,NaN,NaN,NaN,NaN,73,16,34,123.0
습관적으로,510.0,486.0,396.0,343.0,319,309,370,2733.0
시사/보도 프로그램을 통해 정보나 지식을 얻기 위해,364.0,286.0,248.0,186.0,109,127,158,1478.0
음악을 듣기 위해,338.0,229.0,198.0,199.0,138,146,175,1423.0
일이나 공부할 때 지루함을 덜기 위해,588.0,530.0,493.0,594.0,428,441,455,3529.0
재미를 얻기 위해서,238.0,241.0,317.0,281.0,263,214,302,1856.0

In [110]:
# 라디오 청취시 본인의 상황

# 2012
R_situation_12_1 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취시 본인의 상황1_labels'].values, sort = True))
R_situation_12_2 = pd.DataFrame(pd.value_counts(data_2012['라디오 청취시 본인의 상황2_labels'].values, sort = True))

R_situation_12 = pd.concat([R_situation_12_1, R_situation_12_2], axis=1)
R_situation_12['R_situation_12']= R_situation_12.iloc[:, 0:2].sum(axis=1)
R_situation_12

# 2013
R_situation_13_1 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취시 본인의 상황1_labels'].values, sort = True))
R_situation_13_2 = pd.DataFrame(pd.value_counts(data_2013['라디오 청취시 본인의 상황2_labels'].values, sort = True))

R_situation_13 = pd.concat([R_situation_13_1, R_situation_13_2], axis=1)
R_situation_13['R_situation_13']= R_situation_13.iloc[:, 0:2].sum(axis=1)
R_situation_13

# 2014
R_situation_14_1 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취시 본인의 상황1_labels'].values, sort = True))
R_situation_14_2 = pd.DataFrame(pd.value_counts(data_2014['라디오 청취시 본인의 상황2_labels'].values, sort = True))

R_situation_14 = pd.concat([R_situation_14_1, R_situation_14_2], axis=1)
R_situation_14['R_situation_14']= R_situation_14.iloc[:, 0:2].sum(axis=1)

# 2015
R_situation_15_1 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취시 본인의 상황1  _labels'].values, sort = True))
R_situation_15_2 = pd.DataFrame(pd.value_counts(data_2015['라디오 청취시 본인의 상황2  _labels'].values, sort = True))

R_situation_15 = pd.concat([R_situation_15_1, R_situation_15_2], axis=1)
R_situation_15['R_situation_15']= R_situation_15.iloc[:, 0:2].sum(axis=1)

R_situation = pd.concat([R_situation_12['R_situation_12'], R_situation_13['R_situation_13'], R_situation_14['R_situation_14'], R_situation_15['R_situation_15']], axis=1)
R_situation['sum_radio_situation']= R_situation.iloc[:, 0:4].sum(axis=1)
R_situation

,R_situation_12,R_situation_13,R_situation_14,R_situation_15,sum_radio_situation
다른사람이 틀어놓은 것을 청취,202.0,183.0,175.0,172.0,732.0
무응답,159.0,7.0,NaN,NaN,166.0
본인이 직접 듣고 싶은 채널을 찾아서 청취,1482.0,1395.0,1295.0,1553.0,5725.0